import { Category, Supplier, PaintColor, Paint, BlogPost, Blog } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Sơn nội thất", nameEn: "Interior Paint", slug: "son-noi-that" },
  { id: "cat-2", name: "Sơn ngoại thất", nameEn: "Exterior Paint", slug: "son-ngoai-that" },
  { id: "cat-3", name: "Sơn lót kháng kiềm", nameEn: "Primer Paint", slug: "son-lot" },
  { id: "cat-4", name: "Sơn chống thấm", nameEn: "Waterproof Paint", slug: "son-chong-tham" },
  { id: "cat-5", name: "Sơn gỗ & Kim loại", nameEn: "Wood & Metal Paint", slug: "son-go-kim-loai" },
  { id: "cat-6", name: "Sơn đặc biệt", nameEn: "Specialty Paint", slug: "son-dac-biet" },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: "sup-1", name: "Jotun", slug: "jotun" },
  { id: "sup-2", name: "Dulux", slug: "dulux" },
  { id: "sup-3", name: "Nippon Paint", slug: "nippon" },
  { id: "sup-4", name: "TOA Paint", slug: "toa" },
  { id: "sup-5", name: "Kansai Paint", slug: "kansai" },
];

export const MOCK_COLORS: PaintColor[] = [
  { id: "col-1", code: "0001", name: "Trắng Tinh Khôi", nameEn: "Pure White", hex: "#FFFFFF", toneFamily: "neutral", colorFamily: "white" },
  { id: "col-2", code: "1001", name: "Trắng Ngà", nameEn: "Ivory White", hex: "#F5F0E8", toneFamily: "warm", colorFamily: "white" },
  { id: "col-3", code: "1002", name: "Trắng Sữa", nameEn: "Milk White", hex: "#FFF8F0", toneFamily: "warm", colorFamily: "white" },
  { id: "col-4", code: "1003", name: "Trắng Ánh Bạc", nameEn: "Silver White", hex: "#F2F4F5", toneFamily: "cool", colorFamily: "white" },
  { id: "col-5", code: "2001", name: "Kem Vani", nameEn: "Vanilla Cream", hex: "#F3E5D0", toneFamily: "warm", colorFamily: "beige" },
  { id: "col-6", code: "2002", name: "Be Cát", nameEn: "Desert Sand", hex: "#D4C4A8", toneFamily: "warm", colorFamily: "beige" },
  { id: "col-7", code: "2003", name: "Nâu Sữa Nhạt", nameEn: "Latte Light", hex: "#EADCC9", toneFamily: "warm", colorFamily: "beige" },
  { id: "col-8", code: "3001", name: "Xám Nhạt", nameEn: "Light Grey", hex: "#D3D3D3", toneFamily: "neutral", colorFamily: "grey" },
  { id: "col-9", code: "3002", name: "Xám Bạc", nameEn: "Silver Grey", hex: "#C0C0C0", toneFamily: "cool", colorFamily: "grey" },
  { id: "col-10", code: "3003", name: "Xám Than", nameEn: "Charcoal Grey", hex: "#4A4A4A", toneFamily: "neutral", colorFamily: "grey" },
  { id: "col-11", code: "3004", name: "Xám Sương Mù", nameEn: "Mist Grey", hex: "#E2E5E6", toneFamily: "cool", colorFamily: "grey" },
  { id: "col-12", code: "4001", name: "Vàng Chanh", nameEn: "Lemon Yellow", hex: "#F7E856", toneFamily: "warm", colorFamily: "yellow" },
  { id: "col-13", code: "4002", name: "Vàng Nắng", nameEn: "Sunny Gold", hex: "#FFD93D", toneFamily: "warm", colorFamily: "yellow" },
  { id: "col-14", code: "4003", name: "Vàng Hoa Cúc", nameEn: "Marigold", hex: "#F2C94C", toneFamily: "warm", colorFamily: "yellow" },
  { id: "col-15", code: "5001", name: "Cam San Hô", nameEn: "Coral Orange", hex: "#FF7F50", toneFamily: "warm", colorFamily: "orange" },
  { id: "col-16", code: "5002", name: "Cam Đất Ấm", nameEn: "Terracotta", hex: "#CC7722", toneFamily: "earth", colorFamily: "orange" },
  { id: "col-17", code: "6001", name: "Đỏ Rượu Vang", nameEn: "Wine Red", hex: "#722F37", toneFamily: "bold", colorFamily: "red" },
  { id: "col-18", code: "6002", name: "Đỏ Gạch", nameEn: "Brick Red", hex: "#CB4154", toneFamily: "bold", colorFamily: "red" },
  { id: "col-19", code: "7001", name: "Xanh Biển Khơi", nameEn: "Ocean Blue", hex: "#0077B6", toneFamily: "cool", colorFamily: "blue" },
  { id: "col-20", code: "7002", name: "Xanh Pastel", nameEn: "Pastel Blue", hex: "#AEC6CF", toneFamily: "pastel", colorFamily: "blue" },
  { id: "col-21", code: "7003", name: "Xanh Teal Cao Cấp", nameEn: "Teal Blue", hex: "#008080", toneFamily: "bold", colorFamily: "blue" },
  { id: "col-22", code: "8001", name: "Xanh Lá Mạ", nameEn: "Light Green", hex: "#77DD77", toneFamily: "pastel", colorFamily: "green" },
  { id: "col-23", code: "8002", name: "Xanh Rêu", nameEn: "Moss Green", hex: "#4A6741", toneFamily: "earth", colorFamily: "green" },
  { id: "col-24", code: "8003", name: "Xanh Olive", nameEn: "Olive Green", hex: "#808000", toneFamily: "earth", colorFamily: "green" },
  { id: "col-25", code: "9001", name: "Nâu Gỗ Nhạt", nameEn: "Wood Brown", hex: "#8B4513", toneFamily: "earth", colorFamily: "brown" },
  { id: "col-26", code: "9002", name: "Nâu Cà Phê", nameEn: "Coffee Brown", hex: "#6F4E37", toneFamily: "earth", colorFamily: "brown" },
  { id: "col-27", code: "6005", name: "Tím Oải Hương", nameEn: "Lavender", hex: "#D1C4E9", toneFamily: "pastel", colorFamily: "grey" },
  { id: "col-28", code: "7543", name: "Dusty Green", nameEn: "Dusty Green", hex: "#94A396", toneFamily: "earth", colorFamily: "green" },
  { id: "col-29", code: "7686", name: "Mindful Green", nameEn: "Mindful Green", hex: "#778579", toneFamily: "earth", colorFamily: "green" }
];


export const MOCK_PAINTS: Paint[] = [
  // ----------------------------------------------------
  // CATEGORY 1: Sơn Nội Thất (son-noi-that)
  // ----------------------------------------------------
  {
    id: "paint-1",
    sku: "JOT-MAJ-05L",
    name: "Sơn Nội Thất Jotun Majestic Đẹp Hoàn Hảo (Bóng) 5L",
    nameEn: "Jotun Majestic Perfect Beauty Gloss 5L",
    slug: "jotun-majestic-dep-hoan-hao-bong-5l",
    categoryId: "cat-1",
    supplierId: "sup-1",
    description: "Majestic Đẹp Hoàn Hảo là dòng sơn nội thất cao cấp mang lại màu sắc rực rỡ sắc nét và màng sơn bóng mượt dễ lau chùi vượt trội.",
    descriptionEn: "Majestic Perfect Beauty is a premium interior paint that delivers rich, beautiful colors and a smooth, easy-to-clean gloss finish.",
    features: "Kháng khuẩn, Chống nấm mốc, Dễ lau chùi, Hàm lượng VOC cực thấp, Không mùi độc hại",
    featuresEn: "Antibacterial, Anti-fungal, Highly washable, Ultra-low VOC, Odorless",
    application: "Chuẩn bị bề mặt sạch sẽ, khô ráo. Sơn 1 lớp lót kháng kiềm, sau đó sơn 2 lớp phủ hoàn thiện. Thời gian khô giữa các lớp ít nhất là 2 giờ.",
    specifications: "Độ mịn: < 30 micron. Hàm lượng chất rắn: 40%. Tỷ trọng: 1.25 g/cm³.",
    coverage: 12.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "INTERIOR",
    finish: "GLOSS",
    surfaces: ["WALL", "CEILING"],
    volume: 5.00,
    volumeUnit: "L",
    price: 950000.00,
    costPrice: 600000.00,
    stock: 45,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "1002", "2001", "2002", "3001", "3004", "7002", "8001", "6005"],
  },
  {
    id: "paint-2",
    sku: "JOT-MAJ-15L",
    name: "Sơn Nội Thất Jotun Majestic Đẹp Hoàn Hảo (Mờ) 15L",
    nameEn: "Jotun Majestic Perfect Beauty Matte 15L",
    slug: "jotun-majestic-dep-hoan-hao-mo-15l",
    categoryId: "cat-1",
    supplierId: "sup-1",
    description: "Sơn nội thất cao cấp Majestic Đẹp Hoàn Hảo màng sơn mờ sang trọng, che lấp các khuyết điểm trên bề mặt tường tốt nhất.",
    descriptionEn: "Premium Majestic Perfect Beauty paint with elegant matte finish, ideal for hiding minor wall imperfections.",
    features: "Màu sắc sống động, Che phủ vết nứt nhỏ, Dễ lau chùi, Kháng khuẩn mốc",
    featuresEn: "Vibrant colors, Cover hairline cracks, Washable, Anti-fungal",
    application: "Chuẩn bị bề mặt sạch sẽ, khô ráo. Sơn 1 lớp lót kháng kiềm, sau đó sơn 2 lớp phủ hoàn thiện.",
    specifications: "Độ mịn: < 30 micron. Hàm lượng chất rắn: 38%. Tỷ trọng: 1.28 g/cm³.",
    coverage: 12.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "INTERIOR",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 15.00,
    volumeUnit: "L",
    price: 2650000.00,
    costPrice: 1800000.00,
    stock: 20,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "1002", "2001", "2002", "3001", "3002", "3004"],
  },
  {
    id: "paint-3",
    sku: "DUL-5IN1-05L",
    name: "Sơn Nội Thất Dulux Ambiance 5 in 1 Siêu Bóng 5L",
    nameEn: "Dulux Ambiance 5 in 1 Super Gloss 5L",
    slug: "dulux-ambiance-5-in-1-sieu-bong-5l",
    categoryId: "cat-1",
    supplierId: "sup-2",
    description: "Dulux Ambiance 5 in 1 khẳng định chất lượng đỉnh cao với bề mặt siêu láng mịn và những gam màu sắc nét độc đáo.",
    descriptionEn: "Dulux Ambiance 5 in 1 affirms supreme quality with a super smooth surface and unique sharp colors.",
    features: "Ngăn ngừa vi khuẩn, Chùi rửa tối đa, Che lấp khe nứt nhỏ, Chống nấm mốc tốt",
    featuresEn: "Antibacterial, Highly washable, Cover hairline cracks, Anti-mold",
    application: "Chuẩn bị bề mặt sạch sẽ, khô ráo. Sơn 1 lớp lót kháng kiềm, sau đó sơn 2 lớp phủ hoàn thiện.",
    specifications: "Độ mịn: < 25 micron. Hàm lượng chất rắn: 42%.",
    coverage: 11.50,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "INTERIOR",
    finish: "GLOSS",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1100000.00,
    costPrice: 750000.00,
    stock: 35,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "1002", "2001", "2002", "3001", "7002", "8002", "6005"],
  },
  {
    id: "paint-4",
    sku: "NIP-MATE-05L",
    name: "Sơn Nội Thất Nippon Odour-less Chùi Rửa Vượt Trội 5L",
    nameEn: "Nippon Odour-less Premium Washable 5L",
    slug: "nippon-odour-less-chui-rua-vuot-troi-5l",
    categoryId: "cat-1",
    supplierId: "sup-3",
    description: "Sơn nội thất Nippon Odour-less không mùi, hàm lượng VOC rất thấp, thân thiện môi trường và bảo vệ sức khỏe gia đình.",
    descriptionEn: "Nippon Odour-less interior paint is odorless, with low VOC, eco-friendly and safe for health.",
    features: "Hầu như không mùi, Dễ lau chùi tối đa, Chống bám bẩn tốt, Kháng khuẩn cao",
    featuresEn: "Odorless, Washable, Stain resistant, Antibacterial",
    application: "Bề mặt tường cần sạch bụi. Sơn 1 lớp lót, sau đó phủ 2 lớp sơn Odour-less.",
    specifications: "Độ mịn cực cao. Thân thiện môi trường.",
    coverage: 12.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "INTERIOR",
    finish: "SATIN",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 850000.00,
    costPrice: 550000.00,
    stock: 40,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2001", "2002", "3001", "7002", "8002", "6005"],
  },
  {
    id: "paint-5",
    sku: "TOA-SUP-05L",
    name: "Sơn Nội Thất Siêu Cấp TOA SuperShield 5L",
    nameEn: "TOA SuperShield Ultra Premium Interior 5L",
    slug: "toa-supershield-interior-5l",
    categoryId: "cat-1",
    supplierId: "sup-4",
    description: "TOA SuperShield sử dụng công nghệ tự làm sạch tiên tiến chống bám bẩn vượt trội, bảo vệ mảng tường luôn sáng đẹp.",
    descriptionEn: "TOA SuperShield uses self-cleaning technology for superior dirt resistance, keeping walls bright and beautiful.",
    features: "Tự làm sạch, Kháng khuẩn mốc, Độ bền màu 10 năm, Thân thiện môi trường",
    featuresEn: "Self-cleaning, Anti-mold, 10-year color warranty, Eco-friendly",
    application: "Tường sạch. Sơn 1 lót kiềm ngoại thất, 2 phủ màu SuperShield.",
    specifications: "Công nghệ Micro Block từ Mỹ.",
    coverage: 11.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "INTERIOR",
    finish: "SEMI_GLOSS",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 750000.00,
    costPrice: 500000.00,
    stock: 30,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2001", "2002", "3001", "3004"],
  },
  {
    id: "paint-6",
    sku: "KAN-ECO-05L",
    name: "Sơn Nội Thất Kansai Eco Clean Cao Cấp 5L",
    nameEn: "Kansai Eco Clean Premium Interior 5L",
    slug: "kansai-eco-clean-interior-5l",
    categoryId: "cat-1",
    supplierId: "sup-5",
    description: "Kansai Eco Clean là dòng sơn nội thất xanh cao cấp, có khả năng chùi rửa tối ưu và kháng khuẩn cực tốt.",
    descriptionEn: "Kansai Eco Clean is a green premium interior paint, featuring supreme washability and anti-bacterial protection.",
    features: "Chứng chỉ xanh Singapore Green Label, Kháng khuẩn mốc, Lau chùi dễ dàng",
    featuresEn: "Singapore Green Label, Antibacterial, Easy clean",
    application: "Sử dụng trực tiếp sau khi khuấy đều. Pha thêm tối đa 5-10% nước sạch nếu cần.",
    specifications: "Thân thiện môi trường. VOC cực thấp.",
    coverage: 11.80,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "INTERIOR",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 780000.00,
    costPrice: 520000.00,
    stock: 25,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2001", "2002", "3001", "3002"],
  },

  // ----------------------------------------------------
  // CATEGORY 2: Sơn Ngoại Thất (son-ngoai-that)
  // ----------------------------------------------------
  {
    id: "paint-7",
    sku: "JOT-SHI-05L",
    name: "Sơn Ngoại Thất Jotun Jotashield Bền Màu Tối Ưu 5L",
    nameEn: "Jotun Jotashield Extreme Color Durability 5L",
    slug: "jotun-jotashield-ben-mau-toi-uu-5l",
    categoryId: "cat-2",
    supplierId: "sup-1",
    description: "Jotashield Bền Màu Tối Ưu bảo vệ ngôi nhà vượt trội trước khí hậu khắc nghiệt vùng nhiệt đới, giữ màu sắc tươi mới đến 12 năm.",
    descriptionEn: "Jotashield Extreme protects your home against harsh tropical climates, keeping colors fresh for up to 12 years.",
    features: "Chống nắng nóng bức xạ, Chống phai màu do tia UV, Chống bám bụi, Kháng nước tuyệt đối",
    featuresEn: "Heat reflection, Anti-UV, Dirt resistant, 100% Waterproof",
    application: "Tường ngoài nhà cần phẳng mịn, độ ẩm < 16%. Sơn 1-2 lớp lót ngoại thất chống kiềm hóa. Phủ 2 lớp Jotashield.",
    specifications: "Hàm lượng chất rắn: 45%. Chống tia UV: Cực cao. Bảo vệ màng sơn: 12 năm.",
    coverage: 10.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 3 giờ.",
    paintType: "EXTERIOR",
    finish: "SEMI_GLOSS",
    surfaces: ["WALL", "CONCRETE"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1350000.00,
    costPrice: 900000.00,
    stock: 50,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2002", "3002", "3003", "4002", "5002", "8002", "9002"],
  },
  {
    id: "paint-8",
    sku: "DUL-WEA-05L",
    name: "Sơn Ngoại Thất Dulux Weathershield Bóng 5L",
    nameEn: "Dulux Weathershield Gloss Exterior 5L",
    slug: "dulux-weathershield-exterior-gloss-5l",
    categoryId: "cat-2",
    supplierId: "sup-2",
    description: "Sơn Dulux Weathershield là dòng sơn ngoại thất cao cấp bảo vệ tối ưu trước mọi loại thời tiết khắc nghiệt.",
    descriptionEn: "Premium Dulux Weathershield paint provides ultimate protection against all harsh weather conditions.",
    features: "Công nghệ Active Guard chống phai màu, Chống rêu mốc gấp 2 lần, Làm mát ngôi nhà",
    featuresEn: "Active Guard fade protection, Double anti-mold, Keep house cool",
    application: "Chuẩn bị bề mặt sạch sẽ, khô ráo. Sơn 1 lớp lót kháng kiềm, sau đó sơn 2 lớp phủ hoàn thiện.",
    specifications: "Độ bền thời tiết: 8 năm. Kháng muối kiềm: Tốt. Bề mặt: Bóng sang trọng.",
    coverage: 11.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 2-3 giờ.",
    paintType: "EXTERIOR",
    finish: "GLOSS",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1280000.00,
    costPrice: 850000.00,
    stock: 35,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2002", "3002", "3003", "4003", "8002"],
  },
  {
    id: "paint-9",
    sku: "NIP-WEA-05L",
    name: "Sơn Ngoại Thất Nippon WeatherGard Siêu Bóng 5L",
    nameEn: "Nippon WeatherGard Super Gloss 5L",
    slug: "nippon-weathergard-super-gloss-5l",
    categoryId: "cat-2",
    supplierId: "sup-3",
    description: "Nippon WeatherGard bảo vệ kết cấu tường bê tông tuyệt vời trước mưa bão, nắng nhiệt độ cao và ô nhiễm không khí.",
    descriptionEn: "Nippon WeatherGard protects concrete walls from heavy rain, high heat and air pollution.",
    features: "Siêu phản xạ nhiệt, Chống kiềm hóa muối hóa, Chống rêu mốc cực mạnh",
    featuresEn: "Heat reflective, Anti-alkali & salt, Anti-fungal",
    application: "Tường đứng ngoại thất sạch sẽ. Sơn 1 lớp lót WeatherGard Sealer, 2 lớp WeatherGard.",
    specifications: "Công nghệ phản xạ hồng ngoại giảm hấp thụ nhiệt.",
    coverage: 10.50,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 3 giờ.",
    paintType: "EXTERIOR",
    finish: "GLOSS",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1180000.00,
    costPrice: 780000.00,
    stock: 30,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2002", "3002", "3003"],
  },
  {
    id: "paint-10",
    sku: "TOA-NAN-05L",
    name: "Sơn Ngoại Thất TOA NanoShield Bóng 5L",
    nameEn: "TOA NanoShield Gloss Exterior 5L",
    slug: "toa-nanoshield-gloss-5l",
    categoryId: "cat-2",
    supplierId: "sup-4",
    description: "TOA NanoShield chứa các phân tử Nano Silicone giúp chống thấm nước vượt trội và chống bám bẩn tự động.",
    descriptionEn: "TOA NanoShield features Nano Silicone molecules for extreme water resistance and self-cleaning.",
    features: "Công nghệ Teflon bảo vệ bề mặt, Chống thấm nước cực tốt, Kháng kiềm cao",
    featuresEn: "Teflon protective shield, Waterproof, Alkali resistant",
    application: "Làm sạch tường cũ/mới. Sơn lót kháng kiềm TOA. Phủ 2 lớp NanoShield.",
    specifications: "Độ bóng gương cao. Chống bám bẩn tuyệt đối.",
    coverage: 10.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 2-3 giờ.",
    paintType: "EXTERIOR",
    finish: "GLOSS",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 990000.00,
    costPrice: 650000.00,
    stock: 40,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2002", "3002", "3003"],
  },
  {
    id: "paint-11",
    sku: "KAN-ALL-05L",
    name: "Sơn Ngoại Thất Kansai Alushield Chống Phai Màu 5L",
    nameEn: "Kansai Alushield Extreme Weather 5L",
    slug: "kansai-alushield-exterior-5l",
    categoryId: "cat-2",
    supplierId: "sup-5",
    description: "Kansai Alushield là sơn ngoại thất siêu cấp, kháng tia cực tím tối ưu, giảm nhiệt lượng hấp thụ vào nhà.",
    descriptionEn: "Kansai Alushield is a premium exterior paint, preventing UV damage and reducing house heat absorption.",
    features: "Chống nóng hiệu quả, Kháng UV cực đỉnh, Chống rêu mốc 8 năm",
    featuresEn: "Heat reduction, UV resistant, 8-year anti-mold",
    application: "Khuấy đều trước khi dùng. Sơn tối thiểu 2 lớp để đạt độ dày tiêu chuẩn ngoài trời.",
    specifications: "Công nghệ Acrylic cải tiến chống rêu mốc tối đa.",
    coverage: 11.20,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 2-3 giờ.",
    paintType: "EXTERIOR",
    finish: "SEMI_GLOSS",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1050000.00,
    costPrice: 700000.00,
    stock: 35,
    images: ["/product_interior.png"],
    colors: ["0001", "1001", "2002", "3002", "3003"],
  },

  // ----------------------------------------------------
  // CATEGORY 3: Sơn Lót (son-lot)
  // ----------------------------------------------------
  {
    id: "paint-12",
    sku: "JOT-ESS-05L",
    name: "Sơn Lót Kháng Kiềm Jotun Essence 5L",
    nameEn: "Jotun Essence Alkali Resistant Primer 5L",
    slug: "son-lot-jotun-essence-5l",
    categoryId: "cat-3",
    supplierId: "sup-1",
    description: "Sơn lót kháng kiềm nội và ngoại thất giúp cải thiện độ bám dính của sơn phủ và ngăn ngừa ố màu loang lổ.",
    descriptionEn: "Alkali-resistant primer for interior & exterior walls. Enhances topcoat adhesion and prevents paint degradation.",
    features: "Kháng kiềm vượt trội, Chống loang muối, Độ phủ cao, Nhanh khô",
    featuresEn: "Alkali resistant, Salt resistant, High coverage, Quick dry",
    application: "Chuẩn bị bề mặt sạch sẽ, khô ráo. Sơn 1 lớp lót kháng kiềm, sau đó sơn 2 lớp phủ hoàn thiện. Thời gian khô giữa các lớp ít nhất là 2 giờ.",
    specifications: "Độ mịn: < 35 micron. Kháng kiềm: Tuyệt vời. Độ bám dính: Cao.",
    coverage: 12.00,
    coatsRequired: 1,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "PRIMER",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 450000.00,
    costPrice: 300000.00,
    stock: 60,
    images: ["/product_interior.png"],
    colors: ["0001"],
  },
  {
    id: "paint-13",
    sku: "DUL-SUP-05L",
    name: "Sơn Lót Chống Kiềm Cao Cấp Dulux SuperSealer 5L",
    nameEn: "Dulux SuperSealer Premium Primer 5L",
    slug: "son-lot-dulux-supersealer-5l",
    categoryId: "cat-3",
    supplierId: "sup-2",
    description: "Sơn lót Dulux SuperSealer cao cấp bảo vệ tối đa lớp sơn phủ hoàn thiện khỏi chất kiềm ẩm của tường vữa mới trát.",
    descriptionEn: "Premium Dulux SuperSealer primer protects final topcoats from alkalinity of new plasterboard.",
    features: "Kháng kiềm tối đa, Tạo độ bám dính siêu tốt, Giúp sơn phủ bền đẹp",
    featuresEn: "Ultimate alkali resistance, Great adhesion, Enhances topcoat look",
    application: "Tường bê tông khô ráo hoàn toàn. Lăn 1 lớp lót mỏng đều trước khi bả bột hoặc phủ màu.",
    specifications: "Tỷ trọng: 1.25. Không pha chì, thủy ngân.",
    coverage: 11.50,
    coatsRequired: 1,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "PRIMER",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 580000.00,
    costPrice: 380000.00,
    stock: 50,
    images: ["/product_interior.png"],
    colors: ["0001"],
  },
  {
    id: "paint-14",
    sku: "NIP-HIT-05L",
    name: "Sơn Lót Kháng Kiềm Cao Cấp Nippon Hitex 5L",
    nameEn: "Nippon Hitex Premium Sealer 5L",
    slug: "son-lot-nippon-hitex-5l",
    categoryId: "cat-3",
    supplierId: "sup-3",
    description: "Sơn lót Nippon Hitex có khả năng kháng kiềm hóa và kháng muối xuất sắc cho tường ngoài nhà.",
    descriptionEn: "Nippon Hitex primer delivers excellent alkali and salt resistance for exterior concrete walls.",
    features: "Kháng kiềm muối xuất sắc, Chống thấm nhẹ, Tạo nền phẳng mịn màng",
    featuresEn: "Excellent alkali & salt resistance, Waterproofing, Creates smooth base",
    application: "Tường ngoài trời sau khi làm sạch. Lăn đều 1 lớp lót, để khô 2 giờ.",
    specifications: "Thích hợp cho cả tường nội thất và ngoại thất.",
    coverage: 12.00,
    coatsRequired: 1,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "PRIMER",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 490000.00,
    costPrice: 320000.00,
    stock: 45,
    images: ["/product_interior.png"],
    colors: ["0001"],
  },
  {
    id: "paint-15",
    sku: "TOA-SUP-PR-05L",
    name: "Sơn Lót Siêu Chống Kiềm TOA SuperShield Sealer 5L",
    nameEn: "TOA SuperShield Sealer Premium Primer 5L",
    slug: "son-lot-toa-supershield-sealer-5l",
    categoryId: "cat-3",
    supplierId: "sup-4",
    description: "TOA SuperShield Sealer là sơn lót kháng kiềm ngoại thất cao cấp, tăng cường tối đa độ bám dính của lớp sơn phủ.",
    descriptionEn: "TOA SuperShield Sealer is a premium exterior primer, maximizing topcoat adhesion.",
    features: "Tối ưu hóa độ bám dính, Chống loang lổ muối kiềm hiệu quả",
    featuresEn: "Maximizes adhesion, Prevents alkali & salt stains",
    application: "Lăn 1 lớp trên tường sạch trước khi sơn phủ TOA ngoài trời.",
    specifications: "Công nghệ Super Hybrid chống kiềm tối đa.",
    coverage: 11.00,
    coatsRequired: 1,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "PRIMER",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 460000.00,
    costPrice: 310000.00,
    stock: 55,
    images: ["/product_interior.png"],
    colors: ["0001"],
  },
  {
    id: "paint-16",
    sku: "KAN-PRM-05L",
    name: "Sơn Lót Chống Kiềm Kansai Primashield Sealer 5L",
    nameEn: "Kansai Primashield Alkali Sealer 5L",
    slug: "son-lot-kansai-primashield-5l",
    categoryId: "cat-3",
    supplierId: "sup-5",
    description: "Kansai Primashield bảo vệ màng sơn phủ chống lại sự kiềm hóa làm loang màu trên cả bề mặt tường nội ngoại thất.",
    descriptionEn: "Kansai Primashield protects topcoat from alkali attack, suitable for both interior & exterior.",
    features: "Chống kiềm hóa vượt trội, Thân thiện sức khỏe, Độ phủ rộng rãi",
    featuresEn: "Alkali resistant, Safe for health, High coverage",
    application: "Khuấy kỹ trước khi thi công. Sơn 1 lớp lót Primashield rồi sơn phủ.",
    specifications: "Gốc nước cao cấp, không chứa chì.",
    coverage: 11.50,
    coatsRequired: 1,
    dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
    paintType: "PRIMER",
    finish: "MATTE",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 480000.00,
    costPrice: 330000.00,
    stock: 40,
    images: ["/product_interior.png"],
    colors: ["0001"],
  },

  // ----------------------------------------------------
  // CATEGORY 4: Sơn Chống Thấm (son-chong-tham)
  // ----------------------------------------------------
  {
    id: "paint-17",
    sku: "JOT-WAT-20L",
    name: "Sơn Chống Thấm Jotun Waterguard 20kg",
    nameEn: "Jotun Waterguard Waterproofing 20kg",
    slug: "jotun-waterguard-chong-tham-20kg",
    categoryId: "cat-4",
    supplierId: "sup-1",
    description: "Jotun Waterguard bảo vệ tường ngoài nhà khỏi thấm dột do trời mưa, rêu mốc. Sản phẩm dễ sử dụng, che vết nứt nhỏ tuyệt vời.",
    descriptionEn: "Jotun Waterguard protects exterior walls from rain leakage and mold. Easy to apply and covers cracks.",
    features: "Độ đàn hồi cao, Chống thấm nước vượt trội, Không cần pha xi măng",
    featuresEn: "Highly elastic, Water resistant, No cement mixing required",
    application: "Tường sạch bụi. Lăn 2 lớp chống thấm Jotun Waterguard trực tiếp không pha trộn.",
    specifications: "Quy cách đóng gói: 20kg.",
    coverage: 6.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "WATERPROOF",
    finish: "MATTE",
    surfaces: ["WALL", "CONCRETE"],
    volume: 20.00,
    volumeUnit: "kg",
    price: 1850000.00,
    costPrice: 1300000.00,
    stock: 30,
    images: ["/product_interior.png"],
    colors: ["3001", "3002"],
  },
  {
    id: "paint-18",
    sku: "DUL-AQU-06L",
    name: "Chất Chống Thấm Cao Cấp Dulux Aquashield 6kg",
    nameEn: "Dulux Aquashield Premium Waterproofing 6kg",
    slug: "dulux-aquashield-chong-tham-6kg",
    categoryId: "cat-4",
    supplierId: "sup-2",
    description: "Dulux Aquashield bảo vệ tường ngoại thất bền vững khỏi rêu mốc, chống thấm dột tuyệt đối.",
    descriptionEn: "Dulux Aquashield provides extreme waterproof protection for exterior walls against rain and mold.",
    features: "Độ đàn hồi tốt, Ngăn chặn ẩm mốc, Công nghệ chống thấm tiên tiến",
    featuresEn: "Elastic layer, Anti-mold, Advanced waterproof technology",
    application: "Làm sạch rêu mốc tường cũ. Quét 2 lớp Aquashield, giãn cách 4 giờ.",
    specifications: "Công nghệ Hydroshield chống thấm tối tân.",
    coverage: 6.50,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "WATERPROOF",
    finish: "MATTE",
    surfaces: ["WALL", "CONCRETE"],
    volume: 6.00,
    volumeUnit: "kg",
    price: 820000.00,
    costPrice: 550000.00,
    stock: 35,
    images: ["/product_interior.png"],
    colors: ["3001", "3002"],
  },
  {
    id: "paint-19",
    sku: "NIP-WP1-05L",
    name: "Chất Chống Thấm Nippon WP 100 Cao Cấp 5kg",
    nameEn: "Nippon WP 100 Premium Waterproofing 5kg",
    slug: "nippon-wp-100-chong-tham-5kg",
    categoryId: "cat-4",
    supplierId: "sup-3",
    description: "Chất chống thấm Nippon WP 100 chuyên dùng cho các cấu trúc bê tông xi măng ngoài trời.",
    descriptionEn: "Nippon WP 100 is designed for external cement concrete structures waterproofing.",
    features: "Độ bền chống thấm rất cao, Chống kiềm hóa tốt, An sau khi thi công",
    featuresEn: "High durability, Anti-alkali, Safe to apply",
    application: "Trộn hỗn hợp WP100 với xi măng và nước theo tỷ lệ hướng dẫn trước khi quét sơn.",
    specifications: "Gốc Alkyd/Acrylic xi măng đặc biệt.",
    coverage: 6.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4-6 giờ.",
    paintType: "WATERPROOF",
    finish: "MATTE",
    surfaces: ["WALL", "CONCRETE"],
    volume: 5.00,
    volumeUnit: "kg",
    price: 690000.00,
    costPrice: 450000.00,
    stock: 40,
    images: ["/product_interior.png"],
    colors: ["3001", "3002"],
  },
  {
    id: "paint-20",
    sku: "TOA-WP2-20L",
    name: "Chất Chống Thấm Đa Năng TOA Water Block Color 20kg",
    nameEn: "TOA Water Block Color Waterproofing 20kg",
    slug: "toa-water-block-chong-tham-20kg",
    categoryId: "cat-4",
    supplierId: "sup-4",
    description: "Chất chống thấm thế hệ mới TOA Water Block pha màu trực tiếp không cần trộn xi măng xi-măng.",
    descriptionEn: "TOA Water Block Color is a new-generation waterproof coating, tintable without cement mixing.",
    features: "Màu sắc đa dạng, Kháng nước cực cao, Che khuyết điểm bề mặt tốt",
    featuresEn: "Toned colors, Extreme water resistance, Hides cracks",
    application: "Sơn trực tiếp 2-3 lớp lên mảng bê tông cần chống ẩm.",
    specifications: "Màu xám nhạt hoặc xám đậm.",
    coverage: 5.80,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "WATERPROOF",
    finish: "MATTE",
    surfaces: ["WALL", "CONCRETE"],
    volume: 20.00,
    volumeUnit: "kg",
    price: 1680000.00,
    costPrice: 1100000.00,
    stock: 25,
    images: ["/product_interior.png"],
    colors: ["3001", "3002"],
  },
  {
    id: "paint-21",
    sku: "KAN-WTR-20L",
    name: "Sơn Chống Thấm Cao Cấp Kansai WaterProof 20L",
    nameEn: "Kansai WaterProof Premium 20L",
    slug: "kansai-waterproof-chong-tham-20l",
    categoryId: "cat-4",
    supplierId: "sup-5",
    description: "Kansai WaterProof bảo vệ tường ngoài nhà hoàn hảo trước hiện tượng nứt ẩm do trời mưa kéo dài.",
    descriptionEn: "Kansai WaterProof protects exterior walls perfectly from cracks caused by long rains.",
    features: "Công nghệ Silicon biến tính, Chống thấm sâu, Màng sơn dẻo gia",
    featuresEn: "Modified Silicon technology, Deep waterproof, Tough layer",
    application: "Quét 2 lớp đan xen dọc ngang để tạo màng liên kết chống nước tốt nhất.",
    specifications: "Sản phẩm không độc hại.",
    coverage: 6.20,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "WATERPROOF",
    finish: "MATTE",
    surfaces: ["WALL", "CONCRETE"],
    volume: 20.00,
    volumeUnit: "L",
    price: 1720000.00,
    costPrice: 1150000.00,
    stock: 30,
    images: ["/product_interior.png"],
    colors: ["3001", "3002"],
  },

  // ----------------------------------------------------
  // CATEGORY 5: Sơn Gỗ & Kim Loại (son-go-kim-loai)
  // ----------------------------------------------------
  {
    id: "paint-22",
    sku: "JOT-GAR-01L",
    name: "Sơn Dầu Cao Cấp Jotun Gardex (Bóng) 1L",
    nameEn: "Jotun Gardex Premium Gloss Wood & Metal 1L",
    slug: "jotun-gardex-bong-wood-metal-1l",
    categoryId: "cat-5",
    supplierId: "sup-1",
    description: "Gardex là dòng sơn dầu cao cấp dành cho gỗ và kim loại, mang lại vẻ đẹp bóng sang trọng cùng khả năng bảo vệ cực tốt.",
    descriptionEn: "Gardex is a premium wood and metal enamel, delivering luxurious gloss and high protection.",
    features: "Không mùi hắc, Khô nhanh tuyệt vời, Chống rỉ sét tốt, Bền màu lâu dài",
    featuresEn: "Low odor, Quick dry, Rust protection, Color retention",
    application: "Đánh rỉ sét bề mặt kim loại/làm mịn gỗ. Sơn 1 lớp chống rỉ. Phủ 2 lớp Gardex.",
    specifications: "Sơn dầu Alkyd cao cấp.",
    coverage: 14.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6-8 giờ.",
    paintType: "WOOD",
    finish: "GLOSS",
    surfaces: ["WOOD", "METAL"],
    volume: 1.00,
    volumeUnit: "L",
    price: 230000.00,
    costPrice: 150000.00,
    stock: 80,
    images: ["/product_interior.png"],
    colors: ["0001", "3003", "4002", "6001", "8002", "9001"],
  },
  {
    id: "paint-23",
    sku: "DUL-MAX-01L",
    name: "Sơn Dầu Siêu Bóng Dulux Maxilite Wood & Metal 1L",
    nameEn: "Dulux Maxilite Wood & Metal Gloss 1L",
    slug: "dulux-maxilite-wood-metal-1l",
    categoryId: "cat-5",
    supplierId: "sup-2",
    description: "Sơn dầu Dulux Maxilite thích hợp để sơn phủ cho bề mặt kim loại, gỗ trong nhà và ngoài trời.",
    descriptionEn: "Dulux Maxilite enamel is suitable for interior & exterior wood and metal surfaces.",
    features: "Độ phủ cao, Màng sơn bóng mượt, Khô nhanh chóng, Dễ dàng thi công",
    featuresEn: "High coverage, Gloss finish, Quick dry, Easy application",
    application: "Tẩy sạch dầu mỡ bụi bẩn. Quét 2 lớp Maxilite bằng cọ sơn hoặc dung môi pha loãng.",
    specifications: "Hiệu quả kinh tế cao.",
    coverage: 13.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6-8 giờ.",
    paintType: "WOOD",
    finish: "GLOSS",
    surfaces: ["WOOD", "METAL"],
    volume: 1.00,
    volumeUnit: "L",
    price: 180000.00,
    costPrice: 120000.00,
    stock: 90,
    images: ["/product_interior.png"],
    colors: ["0001", "3003", "4002", "9001"],
  },
  {
    id: "paint-24",
    sku: "NIP-BIL-01L",
    name: "Sơn Dầu Cao Cấp Nippon Bilac Cho Gỗ & Sắt 1L",
    nameEn: "Nippon Bilac Wood & Metal Enamel 1L",
    slug: "nippon-bilac-wood-metal-1l",
    categoryId: "cat-5",
    supplierId: "sup-3",
    description: "Nippon Bilac là loại sơn gốc Alkyd cao cấp giúp chống rỉ sét và bảo vệ tốt nhất bề mặt sắt thép.",
    descriptionEn: "Nippon Bilac is a premium Alkyd enamel, preventing rust and protecting metal structures.",
    features: "Chống rỉ sét vượt trội, Màu sắc láng mịn bóng bẩy, Độ bền thời tiết cao",
    featuresEn: "Rust resistant, Smooth gloss, Weather resistant",
    application: "Lăn trực tiếp hoặc pha loãng tối đa 10% dung môi Bilac Thinner.",
    specifications: "Chống rỉ sét ăn mòn xuất sắc.",
    coverage: 13.50,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6 giờ.",
    paintType: "METAL",
    finish: "GLOSS",
    surfaces: ["WOOD", "METAL"],
    volume: 1.00,
    volumeUnit: "L",
    price: 195000.00,
    costPrice: 130000.00,
    stock: 75,
    images: ["/product_interior.png"],
    colors: ["0001", "3003", "4002", "9001"],
  },
  {
    id: "paint-25",
    sku: "TOA-GLI-01L",
    name: "Sơn Dầu Cao Cấp TOA Glipton Cho Kim Loại 1L",
    nameEn: "TOA Glipton Premium Enamel 1L",
    slug: "toa-glipton-metal-1l",
    categoryId: "cat-5",
    supplierId: "sup-4",
    description: "TOA Glipton là dòng sơn alkyd chất lượng thượng hạng mang lại màng sơn bóng mịn như gương.",
    descriptionEn: "TOA Glipton is a top-quality alkyd enamel, delivering a mirror-like gloss finish.",
    features: "Độ bóng gương tuyệt đỉnh, Chống rỉ sét cực tốt, Mùi nhẹ",
    featuresEn: "Mirror gloss finish, Anti-rust, Low odor",
    application: "Tạo bề mặt phẳng nhẵn. Quét sơn dầu Glipton phủ đều 2 lớp.",
    specifications: "Bảo vệ bề mặt sắt thép 8 năm.",
    coverage: 14.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6 giờ.",
    paintType: "METAL",
    finish: "GLOSS",
    surfaces: ["WOOD", "METAL"],
    volume: 1.00,
    volumeUnit: "L",
    price: 190000.00,
    costPrice: 125000.00,
    stock: 85,
    images: ["/product_interior.png"],
    colors: ["0001", "3003", "4002", "9001"],
  },
  {
    id: "paint-26",
    sku: "KAN-FTS-01L",
    name: "Sơn Dầu Kansai Ftax Enamel Cho Gỗ & Sắt 1L",
    nameEn: "Kansai Ftax Enamel Wood & Metal 1L",
    slug: "kansai-ftax-enamel-1l",
    categoryId: "cat-5",
    supplierId: "sup-5",
    description: "Sơn dầu Kansai Ftax bảo vệ chống ăn mòn hiệu quả cho bề mặt gỗ và sắt thép cả trong và ngoài nhà.",
    descriptionEn: "Kansai Ftax protective enamel prevents corrosion on interior & exterior wood & metal.",
    features: "Chống ăn mòn thời tiết tốt, Bám dính cao, Giá thành kinh tế",
    featuresEn: "Corrosion resistant, Great adhesion, Economical",
    application: "Sử dụng cọ quét hoặc súng phun sơn sau khi làm sạch rỉ bề mặt sắt thép.",
    specifications: "Sơn dầu Alkyd bảo vệ tốt.",
    coverage: 13.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6 giờ.",
    paintType: "WOOD",
    finish: "GLOSS",
    surfaces: ["WOOD", "METAL"],
    volume: 1.00,
    volumeUnit: "L",
    price: 185000.00,
    costPrice: 120000.00,
    stock: 70,
    images: ["/product_interior.png"],
    colors: ["0001", "3003", "4002", "9001"],
  },

  // ----------------------------------------------------
  // CATEGORY 6: Sơn Đặc Biệt (son-dac-biet)
  // ----------------------------------------------------
  {
    id: "paint-27",
    sku: "JOT-MAJ-ART-05L",
    name: "Sơn Hiệu Ứng Nghệ Thuật Jotun Majestic Design 5L",
    nameEn: "Jotun Majestic Design Art Effects 5L",
    slug: "jotun-majestic-design-art-effects-5l",
    categoryId: "cat-6",
    supplierId: "sup-1",
    description: "Sơn hiệu ứng Majestic Design mang lại bề mặt tường hoàn thiện lấp lánh như kim cương hay dịu dàng như cát sa mạc.",
    descriptionEn: "Majestic Design creates a sparkling diamond finish or gentle desert sand effects.",
    features: "Hiệu ứng lấp lánh ánh kim, Không mùi độc hại, Lau chùi nhẹ nhàng",
    featuresEn: "Metallic shimmer, Odorless, Lightly washable",
    application: "Lăn 2 lớp sơn lót Majestic Design. Sử dụng bay chuyên dụng quét tạo hiệu ứng cát/ánh kim tùy ý.",
    specifications: "Tạo nét nghệ thuật độc đáo.",
    coverage: 8.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "SPECIALTY",
    finish: "EGGSHELL",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1850000.00,
    costPrice: 1200000.00,
    stock: 15,
    images: ["/product_interior.png"],
    colors: ["1001", "2002", "3004", "7002", "8002", "6005"],
  },
  {
    id: "paint-28",
    sku: "DUL-AMB-TXT-05L",
    name: "Sơn Hiệu Ứng Dulux Ambiance Velvet Gold 5L",
    nameEn: "Dulux Ambiance Velvet Gold Textures 5L",
    slug: "dulux-ambiance-velvet-gold-5l",
    categoryId: "cat-6",
    supplierId: "sup-2",
    description: "Sơn hiệu ứng vải nhung mịn ánh vàng Ambiance Velvet Gold đem lại không gian sống cổ điển sang trọng bậc nhất.",
    descriptionEn: "Dulux Ambiance Velvet Gold delivers a classic ultra-luxurious velvet gold texture.",
    features: "Hiệu ứng vải nhung mịn màng, Sắc vàng ánh kim xa hoa, Chống bám bẩn",
    featuresEn: "Velvet textured finish, Luxurious gold metallic, Stain resistant",
    application: "Tường phẳng tuyệt đối. Sử dụng rulo lăn đều sơn rồi quét chéo cọ để tạo xước nhung ánh vàng.",
    specifications: "Ánh kim loại vàng Velvet ấm áp.",
    coverage: 7.50,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "SPECIALTY",
    finish: "SATIN",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1950000.00,
    costPrice: 1300000.00,
    stock: 10,
    images: ["/product_interior.png"],
    colors: ["2001", "2002", "4002"],
  },
  {
    id: "paint-29",
    sku: "NIP-MOM-05L",
    name: "Sơn Hiệu Ứng Nghệ Thuật Nippon Momento Elegant 5L",
    nameEn: "Nippon Momento Elegant Art Effect 5L",
    slug: "nippon-momento-elegant-5l",
    categoryId: "cat-6",
    supplierId: "sup-3",
    description: "Nippon Momento Elegant mang nét cổ điển độc đáo, khơi gợi cảm hứng sáng tạo vô tận cho bức tường nghệ thuật.",
    descriptionEn: "Nippon Momento Elegant inspires infinite creativity for elegant artistic accent walls.",
    features: "Hiệu ứng vân cát nhám lấp lánh, Độ bền cao, Ít mùi hắc",
    featuresEn: "Sparkling sand texture, High durability, Low odor",
    application: "Lăn sơn lót Primer mờ. Dùng cọ bản to quét chéo tạo hiệu ứng hạt cát nghệ thuật.",
    specifications: "Nhiều chủ đề màu sắc sang trọng.",
    coverage: 8.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
    paintType: "SPECIALTY",
    finish: "SATIN",
    surfaces: ["WALL"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1750000.00,
    costPrice: 1100000.00,
    stock: 12,
    images: ["/product_interior.png"],
    colors: ["1001", "2001", "3004"],
  },
  {
    id: "paint-30",
    sku: "TOA-EPO-05L",
    name: "Sơn Sàn Epoxy TOA 2 Thành Phần Chống Bám Bụi 5L",
    nameEn: "TOA 2-Pack Epoxy Floor Coating 5L",
    slug: "toa-epoxy-floor-paint-5l",
    categoryId: "cat-6",
    supplierId: "sup-4",
    description: "Sơn sàn Epoxy TOA 2 thành phần chịu lực cao lực, thích hợp cho sàn nhà xưởng, tầng hầm hay phòng sạch.",
    descriptionEn: "TOA 2-pack Epoxy Floor coating provides heavy-duty support, perfect for warehouses, basements or cleanrooms.",
    features: "Chịu lực chống trầy xước vượt trội, Chống hóa chất dầu mỡ cực tốt",
    featuresEn: "Extreme abrasion resistance, Chemical & oil resistant",
    application: "Trộn đều phần sơn A và chất đóng rắn B theo đúng tỷ lệ. Lăn rulo trên bề mặt bê tông đã mài nhẵn.",
    specifications: "Kháng trầy xước, va đập mạnh.",
    coverage: 8.50,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 4 giờ. Sử dụng nhẹ: 24 giờ. Đạt độ cứng hoàn toàn: 7 ngày.",
    paintType: "SPECIALTY",
    finish: "SEMI_GLOSS",
    surfaces: ["CONCRETE"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1450000.00,
    costPrice: 950000.00,
    stock: 18,
    images: ["/product_interior.png"],
    colors: ["3002", "3003", "8002"],
  },
  {
    id: "paint-31",
    sku: "KAN-EPO-05L",
    name: "Sơn Sàn Kansai K-Floor Epoxy Chống Trầy Xước 5L",
    nameEn: "Kansai K-Floor Epoxy Floor Coating 5L",
    slug: "kansai-kfloor-epoxy-5l",
    categoryId: "cat-6",
    supplierId: "sup-5",
    description: "Sơn sàn Kansai K-Floor Epoxy bóng cao, chống trơn trượt trầy xước, ngăn ẩm ngăn hóa chất mài mòn.",
    descriptionEn: "Kansai K-Floor Epoxy floor coating features high gloss, anti-slip, scratch-proof, and anti-chemical wear.",
    features: "Màng sơn bóng cao, Chống trơn trượt mài mòn, Dễ vệ sinh làm sạch",
    featuresEn: "High gloss finish, Anti-slip & abrasion proof, Easy clean",
    application: "Bề mặt bê tông phải phẳng mịn, khô sạch độ ẩm < 4%. Sơn phủ 2 lớp Epoxy.",
    specifications: "Epoxy tự phẳng cao cấp.",
    coverage: 9.00,
    coatsRequired: 2,
    dryingTime: "Khô bề mặt: 4 giờ. Sử dụng nhẹ: 24 giờ. Khô hoàn toàn: 7 ngày.",
    paintType: "SPECIALTY",
    finish: "GLOSS",
    surfaces: ["CONCRETE"],
    volume: 5.00,
    volumeUnit: "L",
    price: 1550000.00,
    costPrice: 1000000.00,
    stock: 22,
    images: ["/product_interior.png"],
    colors: ["3002", "3003", "8002"],
  }
];

// Types are imported from "@/types"

export const MOCK_BLOGS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Top 10 Xu Hướng Màu Sơn Nhà Đẹp Trong Năm 2026",
    titleEn: "Top 10 Beautiful Home Paint Color Trends In 2026",
    slug: "top-10-xu-huong-mau-son-nha-2026",
    summary: "Khám phá các tông màu be ấm, xanh rêu thanh bình và màu đất sét được dự báo sẽ thống trị ngành thiết kế kiến trúc nội thất năm 2026.",
    summaryEn: "Explore warm beige, peaceful moss green, and terracotta colors predicted to dominate interior design in 2026.",
    content: "Xu hướng màu sắc năm 2026 chứng kiến sự chuyển dịch mạnh mẽ hướng về thiên nhiên và sự mộc mạc. Các tông màu như Kem Vani, Be Cát và đặc biệt là Xanh Rêu mang lại cảm giác an tâm, nhẹ nhàng cho ngôi nhà của bạn. Bài viết này hướng dẫn bạn cách phối hợp các màu sắc này cho phòng khách, phòng ngủ và mặt tiền nhà hợp xu thế nhất.\n\nSự trỗi dậy của các gam màu Earthy (màu đất) như đất nung, nâu ấm mang lại sự vững chãi và cảm giác kết nối sâu sắc với tự nhiên. Ngược lại, các gam màu Pastel lạnh hay Xanh Teal cao cấp lại tạo điểm nhấn trẻ trung, thời thượng cho những căn hộ cao cấp thành thị.\n\nKhi lựa chọn màu sơn, các chuyên gia thiết kế của Maison de FLOF khuyên bạn nên tuân thủ quy tắc phối màu 60-30-10: 60% cho màu chủ đạo (thường là các màu nhã nhặn như Trắng Ngà, Kem Vani), 30% cho màu cấp 2 (ví dụ Be Cát hoặc Xám Nhạt) và 10% cho màu điểm nhấn nổi bật (như Xanh Teal hoặc Cam Đất).",
    contentEn: "Color trends in 2026 witness a shift towards nature and earthiness. Tones like Vanilla Cream, Desert Sand, and especially Moss Green deliver stability and peace. This guide shares how to combine these colors for living rooms, bedrooms, and exteriors.\n\nThe rise of Earthy colors like terracotta and warm brown brings a grounding effect and a deep connection with nature. On the other hand, cool pastels and premium Teal Blue create vibrant, modern accents for urban apartments.\n\nWhen choosing paint colors, Maison de FLOF's design experts advise adhering to the 60-30-10 rule: 60% for the dominant color (often clean neutrals like Ivory White or Vanilla Cream), 30% for the secondary color (e.g. Desert Sand or Light Grey), and 10% for the outstanding accent color (such as Teal Blue or Terracotta).",
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?q=80&w=800",
    category: "Xu Hướng Thiết Kế",
    categoryEn: "Design Trends",
    author: "Nguyễn Minh Anh - Chuyên Gia Màu Sắc",
    readTime: "5 phút đọc / 5 min read",
    createdAt: "2026-05-15"
  },
  {
    id: "blog-2",
    title: "Hướng Dẫn Tính Định Mức Sơn Đúng Kỹ Thuật Tránh Lãng Phí",
    titleEn: "Guide To Calculating Paint Coverage Properly To Avoid Waste",
    slug: "huong-dan-tinh-dinh-muc-son-dung-ky-thuat",
    summary: "Hướng dẫn chi tiết cách đo diện tích tường thực tế, cách trừ đi diện tích cửa sổ, cửa chính và cách quy đổi số lít sơn thành thùng thực tế.",
    summaryEn: "Detailed guide on measuring real wall areas, subtracting door and window dimensions, and converting paint liters to physical cans.",
    content: "Để bắt đầu sơn nhà, việc tính toán chuẩn lượng sơn vô cùng quan trọng. Công thức chuẩn: Diện tích sơn = 2 x (Chiều dài + Chiều rộng) x Chiều cao - (Diện tích cửa). Thông thường các loại sơn phủ nội thất có định mức 10-12 m2/lít/lớp. Do đó, bạn cần sơn ít nhất 2 lớp phủ và 1 lớp lót để màu sắc đạt chuẩn và bền lâu nhất.\n\nVí dụ: Một phòng khách rộng 4m, dài 5m, cao 3m có 1 cửa chính (2m x 1m) và 2 cửa sổ (1.2m x 1.2m).\n- Tổng diện tích tường: 2 x (4 + 5) x 3 = 54 m².\n- Diện tích cửa: (2 x 1) + 2 x (1.2 x 1.2) = 2 + 2.88 = 4.88 m².\n- Diện tích cần sơn thực tế: 54 - 4.88 = 49.12 m².\n- Lượng sơn lót cần dùng (1 lớp phủ rộng): 49.12 / 12 m²/lít = 4.1 lít sơn lót.\n- Lượng sơn phủ hoàn thiện (2 lớp phủ rộng): 2 x (49.12 / 12 m²/lít) = 8.2 lít sơn phủ.\n\nQuy đổi theo quy cách đóng thùng tại Maison de FLOF:\n- Sơn lót: Mua 1 lon 5 Lít.\n- Sơn phủ: Mua 2 lon 5 Lít (thừa 1.8 lít để dự phòng dặm vá). Việc này giúp bạn tối ưu hóa ngân sách và tránh tình trạng thừa/thiếu sơn khi thi công.",
    contentEn: "To paint a house, calculating the exact quantity of paint is essential. Standard formula: Paint Area = 2 x (Length + Width) x Height - (Doors & Windows Area). Interior paints cover roughly 10-12 sqm/liter/coat. You need 2 top coats and 1 primer coat for perfect results.\n\nExample: A living room 4m wide, 5m long, 3m high with 1 main door (2m x 1m) and 2 windows (1.2m x 1.2m).\n- Total wall area: 2 x (4 + 5) x 3 = 54 sqm.\n- Openings area: (2 x 1) + 2 x (1.2 x 1.2) = 2 + 2.88 = 4.88 sqm.\n- Net paint area: 54 - 4.88 = 49.12 sqm.\n- Primer required (1 coat): 49.12 / 12 sqm/liter = 4.1 liters.\n- Topcoat required (2 coats): 2 x (49.12 / 12 sqm/liter) = 8.2 liters.\n\nConverting to Maison de FLOF's standard can sizes:\n- Primer: Buy 1 can of 5L.\n- Topcoat: Buy 2 cans of 5L (gives you 1.8 liters margin for future touch-ups). This guarantees that you don't overspend on paints.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800",
    category: "Cẩm Nang Thi Công",
    categoryEn: "Execution Guide",
    author: "Kỹ sư Trần Quốc Tuấn - Bộ Phận Kỹ Thuật",
    readTime: "4 phút đọc / 4 min read",
    createdAt: "2026-05-20"
  }
];

