import { PrismaClient, RoleType, PaintType, PaintFinish, SurfaceType } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Starting seed database...");

  // 1. Roles
  const adminRole = await prisma.role.upsert({
    where: { type: RoleType.ADMIN },
    update: {},
    create: { name: "Admin", type: RoleType.ADMIN },
  });

  const staffRole = await prisma.role.upsert({
    where: { type: RoleType.STAFF },
    update: {},
    create: { name: "Staff", type: RoleType.STAFF },
  });

  const customerRole = await prisma.role.upsert({
    where: { type: RoleType.CUSTOMER },
    update: {},
    create: { name: "Customer", type: RoleType.CUSTOMER },
  });

  console.log("Roles seeded successfully.");

  // 2. Users & Customers
  const hashedPassword = await bcrypt.hash("admin123", 12);
  const staffPassword = await bcrypt.hash("staff123", 12);
  const customerPassword = await bcrypt.hash("customer123", 12);

  const adminUser = await prisma.user.upsert({
    where: { email: "admin@sonvn.com" },
    update: {},
    create: {
      email: "admin@sonvn.com",
      password: hashedPassword,
      name: "SONVN Admin",
      phone: "0900000001",
      roleId: adminRole.id,
    },
  });

  const staffUser = await prisma.user.upsert({
    where: { email: "staff@sonvn.com" },
    update: {},
    create: {
      email: "staff@sonvn.com",
      password: staffPassword,
      name: "SONVN Staff",
      phone: "0900000002",
      roleId: staffRole.id,
    },
  });

  const customerUser = await prisma.user.upsert({
    where: { email: "customer1@sonvn.com" },
    update: {},
    create: {
      email: "customer1@sonvn.com",
      password: customerPassword,
      name: "Nguyễn Văn Khách",
      phone: "0900000003",
      roleId: customerRole.id,
    },
  });

  const customerProfile = await prisma.customer.upsert({
    where: { userId: customerUser.id },
    update: {},
    create: {
      userId: customerUser.id,
      customerType: "RETAIL",
    },
  });

  console.log("Users and Profiles seeded successfully.");

  // 3. Suppliers
  const suppliersData = [
    { name: "Jotun", slug: "jotun", website: "https://www.jotun.com/vn", phone: "18001511" },
    { name: "Dulux", slug: "dulux", website: "https://www.dulux.com.vn", phone: "1900555561" },
    { name: "Nippon Paint", slug: "nippon", website: "https://nipponpaint.com.vn", phone: "1800585859" },
    { name: "TOA Paint", slug: "toa", website: "https://www.toagroup.com.vn", phone: "02838155701" },
    { name: "Kansai Paint", slug: "kansai", website: "https://kansaipaint.com.vn", phone: "1900636158" },
  ];

  const suppliersMap: { [key: string]: string } = {};
  for (const s of suppliersData) {
    const supplier = await prisma.supplier.upsert({
      where: { slug: s.slug },
      update: {},
      create: {
        name: s.name,
        slug: s.slug,
        website: s.website,
        phone: s.phone,
        description: `Thương hiệu sơn nước chất lượng hàng đầu tại Việt Nam - ${s.name}`,
      },
    });
    suppliersMap[s.slug] = supplier.id;
  }
  console.log("Suppliers seeded successfully.");

  // 4. Categories
  const categoriesData = [
    { name: "Sơn nội thất", nameEn: "Interior Paint", slug: "son-noi-that", description: "Các dòng sơn tường cao cấp và trung cấp dùng trong nhà, thân thiện môi trường." },
    { name: "Sơn ngoại thất", nameEn: "Exterior Paint", slug: "son-ngoai-that", description: "Các dòng sơn ngoài trời bền màu, chống bám bụi và kháng thời tiết cực tốt." },
    { name: "Sơn lót", nameEn: "Primer Paint", slug: "son-lot", description: "Sơn lót kháng kiềm, tăng độ bám dính và bền màu cho lớp sơn phủ." },
    { name: "Sơn chống thấm", nameEn: "Waterproof Paint", slug: "son-chong-tham", description: "Giải pháp bảo vệ ngôi nhà khỏi thấm dột và rêu mốc do độ ẩm." },
    { name: "Sơn gỗ & Kim loại", nameEn: "Wood & Metal Paint", slug: "son-go-kim-loai", description: "Sơn phủ bảo vệ và trang trí cho bề mặt gỗ, sắt thép." },
    { name: "Sơn đặc biệt", nameEn: "Specialty Paint", slug: "son-dac-biet", description: "Sơn hiệu ứng nghệ thuật, sơn sàn epoxy và sơn chức năng khác." },
  ];

  const categoriesMap: { [key: string]: string } = {};
  for (const c of categoriesData) {
    const category = await prisma.category.upsert({
      where: { slug: c.slug },
      update: {},
      create: {
        name: c.name,
        nameEn: c.nameEn,
        slug: c.slug,
        description: c.description,
      },
    });
    categoriesMap[c.slug] = category.id;
  }
  console.log("Categories seeded successfully.");

  // 5. Color Collections
  const collection2026 = await prisma.colorCollection.upsert({
    where: { slug: "xu-huong-mau-2026" },
    update: {},
    create: {
      name: "Xu Hướng Màu Sắc 2026",
      nameEn: "2026 Color Trends",
      slug: "xu-huong-mau-2026",
      description: "Bộ sưu tập màu sắc mang lại sự bình yên, năng lượng tích cực cho ngôi nhà hiện đại.",
      year: 2026,
    },
  });

  const collectionPeace = await prisma.colorCollection.upsert({
    where: { slug: "khong-gian-binh-yen" },
    update: {},
    create: {
      name: "Không Gian Bình Yên",
      nameEn: "Peaceful Spaces",
      slug: "khong-gian-binh-yen",
      description: "Tổng hợp các tông màu dịu mát, thư giãn lấy cảm hứng từ thiên nhiên.",
      year: 2026,
    },
  });

  console.log("Color collections seeded.");

  // 6. PaintColors (50+ realistic color swatches)
  const colorsData = [
    // Trắng / White
    { code: "0001", name: "Trắng Tinh Khôi", nameEn: "Pure White", hex: "#FFFFFF", rgb: "255,255,255", hsl: "0,0%,100%", toneFamily: "neutral", colorFamily: "white", isPopular: true, collectionId: collectionPeace.id },
    { code: "1001", name: "Trắng Ngà", nameEn: "Ivory White", hex: "#F5F0E8", rgb: "245,240,232", hsl: "37,30%,94%", toneFamily: "warm", colorFamily: "white", isTrending: true, collectionId: collection2026.id },
    { code: "1002", name: "Trắng Sữa", nameEn: "Milk White", hex: "#FFF8F0", rgb: "255,248,240", hsl: "32,100%,97%", toneFamily: "warm", colorFamily: "white" },
    { code: "1003", name: "Trắng Ánh Bạc", nameEn: "Silver White", hex: "#F2F4F5", rgb: "242,244,245", hsl: "200,10%,95%", toneFamily: "cool", colorFamily: "white" },

    // Be / Beige
    { code: "2001", name: "Kem Vani", nameEn: "Vanilla Cream", hex: "#F3E5D0", rgb: "243,229,208", hsl: "36,60%,88%", toneFamily: "warm", colorFamily: "beige", isPopular: true },
    { code: "2002", name: "Be Cát", nameEn: "Desert Sand", hex: "#D4C4A8", rgb: "212,196,168", hsl: "38,36%,75%", toneFamily: "warm", colorFamily: "beige", isTrending: true, collectionId: collection2026.id },
    { code: "2003", name: "Nâu Sữa Nhạt", nameEn: "Latte Light", hex: "#EADCC9", rgb: "234,220,201", hsl: "35,42%,85%", toneFamily: "warm", colorFamily: "beige" },

    // Xám / Grey
    { code: "3001", name: "Xám Nhạt", nameEn: "Light Grey", hex: "#D3D3D3", rgb: "211,211,211", hsl: "0,0%,83%", toneFamily: "neutral", colorFamily: "grey" },
    { code: "3002", name: "Xám Bạc", nameEn: "Silver Grey", hex: "#C0C0C0", rgb: "192,192,192", hsl: "0,0%,75%", toneFamily: "cool", colorFamily: "grey", isPopular: true },
    { code: "3003", name: "Xám Than", nameEn: "Charcoal Grey", hex: "#4A4A4A", rgb: "74,74,74", hsl: "0,0%,29%", toneFamily: "neutral", colorFamily: "grey", isTrending: true },
    { code: "3004", name: "Xám Sương Mù", nameEn: "Mist Grey", hex: "#E2E5E6", rgb: "226,229,230", hsl: "195,7%,89%", toneFamily: "cool", colorFamily: "grey", collectionId: collectionPeace.id },

    // Vàng / Yellow
    { code: "4001", name: "Vàng Chanh", nameEn: "Lemon Yellow", hex: "#F7E856", rgb: "247,232,86", hsl: "54,91%,65%", toneFamily: "warm", colorFamily: "yellow" },
    { code: "4002", name: "Vàng Nắng", nameEn: "Sunny Gold", hex: "#FFD93D", rgb: "255,217,61", hsl: "48,100%,62%", toneFamily: "warm", colorFamily: "yellow", isPopular: true },
    { code: "4003", name: "Vàng Hoa Cúc", nameEn: "Marigold", hex: "#F2C94C", rgb: "242,201,76", hsl: "45,87%,62%", toneFamily: "warm", colorFamily: "yellow" },

    // Cam / Orange
    { code: "5001", name: "Cam San Hô", nameEn: "Coral Orange", hex: "#FF7F50", rgb: "255,127,80", hsl: "16,100%,66%", toneFamily: "warm", colorFamily: "orange", isTrending: true },
    { code: "5002", name: "Cam Đất Ấm", nameEn: "Terracotta", hex: "#CC7722", rgb: "204,119,34", hsl: "30,71%,47%", toneFamily: "earth", colorFamily: "orange", isPopular: true, collectionId: collection2026.id },

    // Đỏ / Red
    { code: "6001", name: "Đỏ Rượu Vang", nameEn: "Wine Red", hex: "#722F37", rgb: "114,47,55", hsl: "353,42%,32%", toneFamily: "bold", colorFamily: "red" },
    { code: "6002", name: "Đỏ Gạch", nameEn: "Brick Red", hex: "#CB4154", rgb: "203,65,84", hsl: "352,57%,53%", toneFamily: "bold", colorFamily: "red", isTrending: true },

    // Xanh dương / Blue
    { code: "7001", name: "Xanh Biển Khơi", nameEn: "Ocean Blue", hex: "#0077B6", rgb: "0,119,182", hsl: "200,100%,36%", toneFamily: "cool", colorFamily: "blue", isPopular: true },
    { code: "7002", name: "Xanh Pastel", nameEn: "Pastel Blue", hex: "#AEC6CF", rgb: "174,198,207", hsl: "196,26%,75%", toneFamily: "pastel", colorFamily: "blue", collectionId: collectionPeace.id },
    { code: "7003", name: "Xanh Teal Cao Cấp", nameEn: "Teal Blue", hex: "#008080", rgb: "0,128,128", hsl: "180,100%,25%", toneFamily: "bold", colorFamily: "blue", isTrending: true, collectionId: collection2026.id },

    // Xanh lá / Green
    { code: "8001", name: "Xanh Lá Mạ", nameEn: "Light Green", hex: "#77DD77", rgb: "119,221,119", hsl: "120,60%,67%", toneFamily: "pastel", colorFamily: "green" },
    { code: "8002", name: "Xanh Rêu", nameEn: "Moss Green", hex: "#4A6741", rgb: "74,103,65", hsl: "106,23%,33%", toneFamily: "earth", colorFamily: "green", isPopular: true },
    { code: "8003", name: "Xanh Olive", nameEn: "Olive Green", hex: "#808000", rgb: "128,128,0", hsl: "60,100%,25%", toneFamily: "earth", colorFamily: "green", collectionId: collectionPeace.id },

    // Nâu / Brown
    { code: "9001", name: "Nâu Gỗ Nhạt", nameEn: "Wood Brown", hex: "#8B4513", rgb: "139,69,19", hsl: "25,76%,31%", toneFamily: "earth", colorFamily: "brown" },
    { code: "9002", name: "Nâu Cà Phê", nameEn: "Coffee Brown", hex: "#6F4E37", rgb: "111,78,55", hsl: "25,34%,33%", toneFamily: "earth", colorFamily: "brown", isPopular: true, collectionId: collection2026.id }
  ];

  const colorsMap: { [code: string]: string } = {};
  for (const c of colorsData) {
    const color = await prisma.paintColor.upsert({
      where: { code: c.code },
      update: {},
      create: {
        code: c.code,
        name: c.name,
        nameEn: c.nameEn,
        hex: c.hex,
        rgb: c.rgb,
        hsl: c.hsl,
        toneFamily: c.toneFamily,
        colorFamily: c.colorFamily,
        isPopular: c.isPopular,
        isTrending: c.isTrending,
        collectionId: c.collectionId,
      },
    });
    colorsMap[c.code] = color.id;
  }
  console.log("PaintColors seeded successfully.");

  // 7. Paint Products (VN Market Paints)
  const paintsData = [
    // ----------------------------------------------------
    // CATEGORY 1: Sơn Nội Thất (son-noi-that)
    // ----------------------------------------------------
    {
      sku: "JOT-MAJ-05L",
      name: "Sơn Nội Thất Jotun Majestic Đẹp Hoàn Hảo (Bóng) 5L",
      nameEn: "Jotun Majestic Perfect Beauty Gloss 5L",
      slug: "jotun-majestic-dep-hoan-hao-bong-5l",
      categoryId: categoriesMap["son-noi-that"],
      supplierId: suppliersMap["jotun"],
      description: "Majestic Đẹp Hoàn Hảo là dòng sơn nội thất cao cấp mang lại màu sắc rực rỡ sắc nét và màng sơn bóng mượt dễ lau chùi vượt trội.",
      descriptionEn: "Majestic Perfect Beauty is a premium interior paint that delivers rich, beautiful colors and a smooth, easy-to-clean gloss finish.",
      features: "Kháng khuẩn, Chống nấm mốc, Dễ lau chùi, Hàm lượng VOC cực thấp, Không mùi độc hại",
      featuresEn: "Antibacterial, Anti-fungal, Highly washable, Ultra-low VOC, Odorless",
      coverage: 12.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.INTERIOR,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WALL, SurfaceType.CEILING],
      volume: 5.00,
      volumeUnit: "L",
      price: 950000.00,
      costPrice: 600000.00,
      stock: 45,
      isFeatured: true,
      colors: ["0001", "1001", "1002", "2001", "2002", "3001", "3004", "7002", "8001"],
    },
    {
      sku: "JOT-MAJ-15L",
      name: "Sơn Nội Thất Jotun Majestic Đẹp Hoàn Hảo (Mờ) 15L",
      nameEn: "Jotun Majestic Perfect Beauty Matte 15L",
      slug: "jotun-majestic-dep-hoan-hao-mo-15l",
      categoryId: categoriesMap["son-noi-that"],
      supplierId: suppliersMap["jotun"],
      description: "Sơn nội thất cao cấp Majestic Đẹp Hoàn Hảo màng sơn mờ sang trọng, che lấp các khuyết điểm trên bề mặt tường tốt nhất.",
      descriptionEn: "Premium Majestic Perfect Beauty paint with elegant matte finish, ideal for hiding minor wall imperfections.",
      features: "Màu sắc sống động, Che phủ vết nứt nhỏ, Dễ lau chùi, Kháng khuẩn mốc",
      featuresEn: "Vibrant colors, Cover hairline cracks, Washable, Anti-fungal",
      coverage: 12.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.INTERIOR,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 15.00,
      volumeUnit: "L",
      price: 2650000.00,
      costPrice: 1800000.00,
      stock: 20,
      isFeatured: true,
      colors: ["0001", "1001", "1002", "2001", "2002", "3001", "3002", "3004"],
    },
    {
      sku: "DUL-5IN1-05L",
      name: "Sơn Nội Thất Dulux Ambiance 5 in 1 Siêu Bóng 5L",
      nameEn: "Dulux Ambiance 5 in 1 Super Gloss 5L",
      slug: "dulux-ambiance-5-in-1-sieu-bong-5l",
      categoryId: categoriesMap["son-noi-that"],
      supplierId: suppliersMap["dulux"],
      description: "Dulux Ambiance 5 in 1 khẳng định chất lượng đỉnh cao với bề mặt siêu láng mịn và những gam màu sắc nét độc đáo.",
      descriptionEn: "Dulux Ambiance 5 in 1 affirms supreme quality with a super smooth surface and unique sharp colors.",
      features: "Ngăn ngừa vi khuẩn, Chùi rửa tối đa, Che lấp khe nứt nhỏ, Chống nấm mốc tốt",
      featuresEn: "Antibacterial, Highly washable, Cover hairline cracks, Anti-mold",
      coverage: 11.50,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.INTERIOR,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1100000.00,
      costPrice: 750000.00,
      stock: 35,
      isFeatured: false,
      colors: ["0001", "1001", "1002", "2001", "2002", "3001", "7002", "8002"],
    },
    {
      sku: "NIP-MATE-05L",
      name: "Sơn Nội Thất Nippon Odour-less Chùi Rửa Vượt Trội 5L",
      nameEn: "Nippon Odour-less Premium Washable 5L",
      slug: "nippon-odour-less-chui-rua-vuot-troi-5l",
      categoryId: categoriesMap["son-noi-that"],
      supplierId: suppliersMap["nippon"],
      description: "Sơn nội thất Nippon Odour-less không mùi, hàm lượng VOC rất thấp, thân thiện môi trường và bảo vệ sức khỏe gia đình.",
      descriptionEn: "Nippon Odour-less interior paint is odorless, with low VOC, eco-friendly and safe for health.",
      features: "Hầu như không mùi, Dễ lau chùi tối đa, Chống bám bẩn tốt, Kháng khuẩn cao",
      featuresEn: "Odorless, Washable, Stain resistant, Antibacterial",
      coverage: 12.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.INTERIOR,
      finish: PaintFinish.SATIN,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 850000.00,
      costPrice: 550000.00,
      stock: 40,
      isFeatured: false,
      colors: ["0001", "1001", "2001", "2002", "3001", "7002", "8002"],
    },
    {
      sku: "TOA-SUP-05L",
      name: "Sơn Nội Thất Siêu Cấp TOA SuperShield 5L",
      nameEn: "TOA SuperShield Ultra Premium Interior 5L",
      slug: "toa-supershield-interior-5l",
      categoryId: categoriesMap["son-noi-that"],
      supplierId: suppliersMap["toa"],
      description: "TOA SuperShield sử dụng công nghệ tự làm sạch tiên tiến chống bám bẩn vượt trội, bảo vệ mảng tường luôn sáng đẹp.",
      descriptionEn: "TOA SuperShield uses self-cleaning technology for superior dirt resistance, keeping walls bright and beautiful.",
      features: "Tự làm sạch, Kháng khuẩn mốc, Độ bền màu 10 năm, Thân thiện môi trường",
      featuresEn: "Self-cleaning, Anti-mold, 10-year color warranty, Eco-friendly",
      coverage: 11.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.INTERIOR,
      finish: PaintFinish.SEMI_GLOSS,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 750000.00,
      costPrice: 500000.00,
      stock: 30,
      isFeatured: false,
      colors: ["0001", "1001", "2001", "2002", "3001", "3004"],
    },
    {
      sku: "KAN-ECO-05L",
      name: "Sơn Nội Thất Kansai Eco Clean Cao Cấp 5L",
      nameEn: "Kansai Eco Clean Premium Interior 5L",
      slug: "kansai-eco-clean-interior-5l",
      categoryId: categoriesMap["son-noi-that"],
      supplierId: suppliersMap["kansai"],
      description: "Kansai Eco Clean là dòng sơn nội thất xanh cao cấp, có khả năng chùi rửa tối ưu và kháng khuẩn cực tốt.",
      descriptionEn: "Kansai Eco Clean is a green premium interior paint, featuring supreme washability and anti-bacterial protection.",
      features: "Chứng chỉ xanh Singapore Green Label, Kháng khuẩn mốc, Lau chùi dễ dàng",
      featuresEn: "Singapore Green Label, Antibacterial, Easy clean",
      coverage: 11.80,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.INTERIOR,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 780000.00,
      costPrice: 520000.00,
      stock: 25,
      isFeatured: false,
      colors: ["0001", "1001", "2001", "2002", "3001", "3002"],
    },

    // ----------------------------------------------------
    // CATEGORY 2: Sơn Ngoại Thất (son-ngoai-that)
    // ----------------------------------------------------
    {
      sku: "JOT-SHI-05L",
      name: "Sơn Ngoại Thất Jotun Jotashield Bền Màu Tối Ưu 5L",
      nameEn: "Jotun Jotashield Extreme Color Durability 5L",
      slug: "jotun-jotashield-ben-mau-toi-uu-5l",
      categoryId: categoriesMap["son-ngoai-that"],
      supplierId: suppliersMap["jotun"],
      description: "Jotashield Bền Màu Tối Ưu bảo vệ ngôi nhà vượt trội trước khí hậu khắc nghiệt vùng nhiệt đới, giữ màu sắc tươi mới đến 12 năm.",
      descriptionEn: "Jotashield Extreme protects your home against harsh tropical climates, keeping colors fresh for up to 12 years.",
      features: "Chống nắng nóng bức xạ, Chống phai màu do tia UV, Chống bám bụi, Kháng nước tuyệt đối",
      featuresEn: "Heat reflection, Anti-UV, Dirt resistant, 100% Waterproof",
      coverage: 10.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 3 giờ.",
      paintType: PaintType.EXTERIOR,
      finish: PaintFinish.SEMI_GLOSS,
      surfaces: [SurfaceType.WALL, SurfaceType.CONCRETE],
      volume: 5.00,
      volumeUnit: "L",
      price: 1350000.00,
      costPrice: 900000.00,
      stock: 50,
      isFeatured: true,
      colors: ["0001", "1001", "2002", "3002", "3003", "4002", "5002", "8002", "9002"],
    },
    {
      sku: "DUL-WEA-05L",
      name: "Sơn Ngoại Thất Dulux Weathershield Bóng 5L",
      nameEn: "Dulux Weathershield Gloss Exterior 5L",
      slug: "dulux-weathershield-exterior-gloss-5l",
      categoryId: categoriesMap["son-ngoai-that"],
      supplierId: suppliersMap["dulux"],
      description: "Sơn Dulux Weathershield là dòng sơn ngoại thất cao cấp bảo vệ tối ưu trước mọi loại thời tiết khắc nghiệt.",
      descriptionEn: "Premium Dulux Weathershield paint provides ultimate protection against all harsh weather conditions.",
      features: "Công nghệ Active Guard chống phai màu, Chống rêu mốc gấp 2 lần, Làm mát ngôi nhà",
      featuresEn: "Active Guard fade protection, Double anti-mold, Keep house cool",
      coverage: 11.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 2-3 giờ.",
      paintType: PaintType.EXTERIOR,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1280000.00,
      costPrice: 850000.00,
      stock: 35,
      isFeatured: true,
      colors: ["0001", "1001", "2002", "3002", "3003", "4003", "8002"],
    },
    {
      sku: "NIP-WEA-05L",
      name: "Sơn Ngoại Thất Nippon WeatherGard Siêu Bóng 5L",
      nameEn: "Nippon WeatherGard Super Gloss 5L",
      slug: "nippon-weathergard-super-gloss-5l",
      categoryId: categoriesMap["son-ngoai-that"],
      supplierId: suppliersMap["nippon"],
      description: "Nippon WeatherGard bảo vệ kết cấu tường bê tông tuyệt vời trước mưa bão, nắng nhiệt độ cao và ô nhiễm không khí.",
      descriptionEn: "Nippon WeatherGard protects concrete walls from heavy rain, high heat and air pollution.",
      features: "Siêu phản xạ nhiệt, Chống kiềm hóa muối hóa, Chống rêu mốc cực mạnh",
      featuresEn: "Heat reflective, Anti-alkali & salt, Anti-fungal",
      coverage: 10.50,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 3 giờ.",
      paintType: PaintType.EXTERIOR,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1180000.00,
      costPrice: 780000.00,
      stock: 30,
      isFeatured: false,
      colors: ["0001", "1001", "2002", "3002", "3003"],
    },
    {
      sku: "TOA-NAN-05L",
      name: "Sơn Ngoại Thất TOA NanoShield Bóng 5L",
      nameEn: "TOA NanoShield Gloss Exterior 5L",
      slug: "toa-nanoshield-gloss-5l",
      categoryId: categoriesMap["son-ngoai-that"],
      supplierId: suppliersMap["toa"],
      description: "TOA NanoShield chứa các phân tử Nano Silicone giúp chống thấm nước vượt trội và chống bám bẩn tự động.",
      descriptionEn: "TOA NanoShield features Nano Silicone molecules for extreme water resistance and self-cleaning.",
      features: "Công nghệ Teflon bảo vệ bề mặt, Chống thấm nước cực tốt, Kháng kiềm cao",
      featuresEn: "Teflon protective shield, Waterproof, Alkali resistant",
      coverage: 10.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 2-3 giờ.",
      paintType: PaintType.EXTERIOR,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 990000.00,
      costPrice: 650000.00,
      stock: 40,
      isFeatured: false,
      colors: ["0001", "1001", "2002", "3002", "3003"],
    },
    {
      sku: "KAN-ALL-05L",
      name: "Sơn Ngoại Thất Kansai Alushield Chống Phai Màu 5L",
      nameEn: "Kansai Alushield Extreme Weather 5L",
      slug: "kansai-alushield-exterior-5l",
      categoryId: categoriesMap["son-ngoai-that"],
      supplierId: suppliersMap["kansai"],
      description: "Kansai Alushield là sơn ngoại thất siêu cấp, kháng tia cực tím tối ưu, giảm nhiệt lượng hấp thụ vào nhà.",
      descriptionEn: "Kansai Alushield is a premium exterior paint, preventing UV damage and reducing house heat absorption.",
      features: "Chống nóng hiệu quả, Kháng UV cực đỉnh, Chống rêu mốc 8 năm",
      featuresEn: "Heat reduction, UV resistant, 8-year anti-mold",
      coverage: 11.20,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 1 giờ. Sơn lớp tiếp theo: 2-3 giờ.",
      paintType: PaintType.EXTERIOR,
      finish: PaintFinish.SEMI_GLOSS,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1050000.00,
      costPrice: 700000.00,
      stock: 35,
      isFeatured: false,
      colors: ["0001", "1001", "2002", "3002", "3003"],
    },

    // ----------------------------------------------------
    // CATEGORY 3: Sơn Lót (son-lot)
    // ----------------------------------------------------
    {
      sku: "JOT-ESS-05L",
      name: "Sơn Lót Kháng Kiềm Jotun Essence 5L",
      nameEn: "Jotun Essence Alkali Resistant Primer 5L",
      slug: "son-lot-jotun-essence-5l",
      categoryId: categoriesMap["son-lot"],
      supplierId: suppliersMap["jotun"],
      description: "Sơn lót kháng kiềm nội và ngoại thất giúp cải thiện độ bám dính của sơn phủ và ngăn ngừa ố màu loang lổ.",
      descriptionEn: "Alkali-resistant primer for interior & exterior walls. Enhances topcoat adhesion and prevents paint degradation.",
      features: "Kháng kiềm vượt trội, Chống loang muối, Độ phủ cao, Nhanh khô",
      featuresEn: "Alkali resistant, Salt resistant, High coverage, Quick dry",
      coverage: 12.00,
      coatsRequired: 1,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.PRIMER,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 450000.00,
      costPrice: 300000.00,
      stock: 60,
      colors: ["0001"],
    },
    {
      sku: "DUL-SUP-05L",
      name: "Sơn Lót Chống Kiềm Cao Cấp Dulux SuperSealer 5L",
      nameEn: "Dulux SuperSealer Premium Primer 5L",
      slug: "son-lot-dulux-supersealer-5l",
      categoryId: categoriesMap["son-lot"],
      supplierId: suppliersMap["dulux"],
      description: "Sơn lót Dulux SuperSealer cao cấp bảo vệ tối đa lớp sơn phủ hoàn thiện khỏi chất kiềm ẩm của tường vữa mới trát.",
      descriptionEn: "Premium Dulux SuperSealer primer protects final topcoats from alkalinity of new plasterboard.",
      features: "Kháng kiềm tối đa, Tạo độ bám dính siêu tốt, Giúp sơn phủ bền đẹp",
      featuresEn: "Ultimate alkali resistance, Great adhesion, Enhances topcoat look",
      coverage: 11.50,
      coatsRequired: 1,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.PRIMER,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 580000.00,
      costPrice: 380000.00,
      stock: 50,
      colors: ["0001"],
    },
    {
      sku: "NIP-HIT-05L",
      name: "Sơn Lót Kháng Kiềm Cao Cấp Nippon Hitex 5L",
      nameEn: "Nippon Hitex Premium Sealer 5L",
      slug: "son-lot-nippon-hitex-5l",
      categoryId: categoriesMap["son-lot"],
      supplierId: suppliersMap["nippon"],
      description: "Sơn lót Nippon Hitex có khả năng kháng kiềm hóa và kháng muối xuất sắc cho tường ngoài nhà.",
      descriptionEn: "Nippon Hitex primer delivers excellent alkali and salt resistance for exterior concrete walls.",
      features: "Kháng kiềm muối xuất sắc, Chống thấm nhẹ, Tạo nền phẳng mịn màng",
      featuresEn: "Excellent alkali & salt resistance, Waterproofing, Creates smooth base",
      coverage: 12.00,
      coatsRequired: 1,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.PRIMER,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 490000.00,
      costPrice: 320000.00,
      stock: 45,
      colors: ["0001"],
    },
    {
      sku: "TOA-SUP-PR-05L",
      name: "Sơn Lót Siêu Chống Kiềm TOA SuperShield Sealer 5L",
      nameEn: "TOA SuperShield Sealer Premium Primer 5L",
      slug: "son-lot-toa-supershield-sealer-5l",
      categoryId: categoriesMap["son-lot"],
      supplierId: suppliersMap["toa"],
      description: "TOA SuperShield Sealer là sơn lót kháng kiềm ngoại thất cao cấp, tăng cường tối đa độ bám dính của lớp sơn phủ.",
      descriptionEn: "TOA SuperShield Sealer is a premium exterior primer, maximizing topcoat adhesion.",
      features: "Tối ưu hóa độ bám dính, Chống loang lổ muối kiềm hiệu quả",
      featuresEn: "Maximizes adhesion, Prevents alkali & salt stains",
      coverage: 11.00,
      coatsRequired: 1,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.PRIMER,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 460000.00,
      costPrice: 310000.00,
      stock: 55,
      colors: ["0001"],
    },
    {
      sku: "KAN-PRM-05L",
      name: "Sơn Lót Chống Kiềm Kansai Primashield Sealer 5L",
      nameEn: "Kansai Primashield Alkali Sealer 5L",
      slug: "son-lot-kansai-primashield-5l",
      categoryId: categoriesMap["son-lot"],
      supplierId: suppliersMap["kansai"],
      description: "Kansai Primashield bảo vệ màng sơn phủ chống lại sự kiềm hóa làm loang màu trên cả bề mặt tường nội ngoại thất.",
      descriptionEn: "Kansai Primashield protects topcoat from alkali attack, suitable for both interior & exterior.",
      features: "Chống kiềm hóa vượt trội, Thân thiện sức khỏe, Độ phủ rộng rãi",
      featuresEn: "Alkali resistant, Safe for health, High coverage",
      coverage: 11.50,
      coatsRequired: 1,
      dryingTime: "Khô bề mặt: 30 phút. Sơn lớp tiếp theo: 2 giờ.",
      paintType: PaintType.PRIMER,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 480000.00,
      costPrice: 330000.00,
      stock: 40,
      colors: ["0001"],
    },

    // ----------------------------------------------------
    // CATEGORY 4: Sơn Chống Thấm (son-chong-tham)
    // ----------------------------------------------------
    {
      sku: "JOT-WAT-20L",
      name: "Sơn Chống Thấm Jotun Waterguard 20kg",
      nameEn: "Jotun Waterguard Waterproofing 20kg",
      slug: "jotun-waterguard-chong-tham-20kg",
      categoryId: categoriesMap["son-chong-tham"],
      supplierId: suppliersMap["jotun"],
      description: "Jotun Waterguard bảo vệ tường ngoài nhà khỏi thấm dột do trời mưa, rêu mốc. Sản phẩm dễ sử dụng, che vết nứt nhỏ tuyệt vời.",
      descriptionEn: "Jotun Waterguard protects exterior walls from rain leakage and mold. Easy to apply and covers cracks.",
      features: "Độ đàn hồi cao, Chống thấm nước vượt trội, Không cần pha xi măng",
      featuresEn: "Highly elastic, Water resistant, No cement mixing required",
      coverage: 6.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.WATERPROOF,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL, SurfaceType.CONCRETE],
      volume: 20.00,
      volumeUnit: "kg",
      price: 1850000.00,
      costPrice: 1300000.00,
      stock: 30,
      colors: ["3001", "3002"],
    },
    {
      sku: "DUL-AQU-06L",
      name: "Chất Chống Thấm Cao Cấp Dulux Aquashield 6kg",
      nameEn: "Dulux Aquashield Premium Waterproofing 6kg",
      slug: "dulux-aquashield-chong-tham-6kg",
      categoryId: categoriesMap["son-chong-tham"],
      supplierId: suppliersMap["dulux"],
      description: "Dulux Aquashield bảo vệ tường ngoại thất bền vững khỏi rêu mốc, chống thấm dột tuyệt đối.",
      descriptionEn: "Dulux Aquashield provides extreme waterproof protection for exterior walls against rain and mold.",
      features: "Độ đàn hồi tốt, Ngăn chặn ẩm mốc, Công nghệ chống thấm tiên tiến",
      featuresEn: "Elastic layer, Anti-mold, Advanced waterproof technology",
      coverage: 6.50,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.WATERPROOF,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL, SurfaceType.CONCRETE],
      volume: 6.00,
      volumeUnit: "kg",
      price: 820000.00,
      costPrice: 550000.00,
      stock: 35,
      colors: ["3001", "3002"],
    },
    {
      sku: "NIP-WP1-05L",
      name: "Chất Chống Thấm Nippon WP 100 Cao Cấp 5kg",
      nameEn: "Nippon WP 100 Premium Waterproofing 5kg",
      slug: "nippon-wp-100-chong-tham-5kg",
      categoryId: categoriesMap["son-chong-tham"],
      supplierId: suppliersMap["nippon"],
      description: "Chất chống thấm Nippon WP 100 chuyên dùng cho các cấu trúc bê tông xi măng ngoài trời.",
      descriptionEn: "Nippon WP 100 is designed for external cement concrete structures waterproofing.",
      features: "Độ bền chống thấm rất cao, Chống kiềm hóa tốt, An toàn khi thi công",
      featuresEn: "High durability, Anti-alkali, Safe to apply",
      coverage: 6.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4-6 giờ.",
      paintType: PaintType.WATERPROOF,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL, SurfaceType.CONCRETE],
      volume: 5.00,
      volumeUnit: "kg",
      price: 690000.00,
      costPrice: 450000.00,
      stock: 40,
      colors: ["3001", "3002"],
    },
    {
      sku: "TOA-WP2-20L",
      name: "Chất Chống Thấm Đa Năng TOA Water Block Color 20kg",
      nameEn: "TOA Water Block Color Waterproofing 20kg",
      slug: "toa-water-block-chong-tham-20kg",
      categoryId: categoriesMap["son-chong-tham"],
      supplierId: suppliersMap["toa"],
      description: "Chất chống thấm thế hệ mới TOA Water Block pha màu trực tiếp không cần trộn xi măng xi-măng.",
      descriptionEn: "TOA Water Block Color is a new-generation waterproof coating, tintable without cement mixing.",
      features: "Màu sắc đa dạng, Kháng nước cực cao, Che khuyết điểm bề mặt tốt",
      featuresEn: "Toned colors, Extreme water resistance, Hides cracks",
      coverage: 5.80,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.WATERPROOF,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL, SurfaceType.CONCRETE],
      volume: 20.00,
      volumeUnit: "kg",
      price: 1680000.00,
      costPrice: 1100000.00,
      stock: 25,
      colors: ["3001", "3002"],
    },
    {
      sku: "KAN-WTR-20L",
      name: "Sơn Chống Thấm Cao Cấp Kansai WaterProof 20L",
      nameEn: "Kansai WaterProof Premium 20L",
      slug: "kansai-waterproof-chong-tham-20l",
      categoryId: categoriesMap["son-chong-tham"],
      supplierId: suppliersMap["kansai"],
      description: "Kansai WaterProof bảo vệ tường ngoài nhà hoàn hảo trước hiện tượng nứt ẩm do trời mưa kéo dài.",
      descriptionEn: "Kansai WaterProof protects exterior walls perfectly from cracks caused by long rains.",
      features: "Công nghệ Silicon biến tính, Chống thấm sâu, Màng sơn dẻo gia",
      featuresEn: "Modified Silicon technology, Deep waterproof, Tough layer",
      coverage: 6.20,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.WATERPROOF,
      finish: PaintFinish.MATTE,
      surfaces: [SurfaceType.WALL, SurfaceType.CONCRETE],
      volume: 20.00,
      volumeUnit: "L",
      price: 1720000.00,
      costPrice: 1150000.00,
      stock: 30,
      colors: ["3001", "3002"],
    },

    // ----------------------------------------------------
    // CATEGORY 5: Sơn Gỗ & Kim Loại (son-go-kim-loai)
    // ----------------------------------------------------
    {
      sku: "JOT-GAR-01L",
      name: "Sơn Dầu Cao Cấp Jotun Gardex (Bóng) 1L",
      nameEn: "Jotun Gardex Premium Gloss Wood & Metal 1L",
      slug: "jotun-gardex-bong-wood-metal-1l",
      categoryId: categoriesMap["son-go-kim-loai"],
      supplierId: suppliersMap["jotun"],
      description: "Gardex là dòng sơn dầu cao cấp dành cho gỗ và kim loại, mang lại vẻ đẹp bóng sang trọng cùng khả năng bảo vệ cực tốt.",
      descriptionEn: "Gardex is a premium wood and metal enamel, delivering luxurious gloss and high protection.",
      features: "Không mùi hắc, Khô nhanh tuyệt vời, Chống rỉ sét tốt, Bền màu lâu dài",
      featuresEn: "Low odor, Quick dry, Rust protection, Color retention",
      coverage: 14.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6-8 giờ.",
      paintType: PaintType.WOOD,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WOOD, SurfaceType.METAL],
      volume: 1.00,
      volumeUnit: "L",
      price: 230000.00,
      costPrice: 150000.00,
      stock: 80,
      colors: ["0001", "3003", "4002", "6001", "8002", "9001"],
    },
    {
      sku: "DUL-MAX-01L",
      name: "Sơn Dầu Siêu Bóng Dulux Maxilite Wood & Metal 1L",
      nameEn: "Dulux Maxilite Wood & Metal Gloss 1L",
      slug: "dulux-maxilite-wood-metal-1l",
      categoryId: categoriesMap["son-go-kim-loai"],
      supplierId: suppliersMap["dulux"],
      description: "Sơn dầu Dulux Maxilite thích hợp để sơn phủ cho bề mặt kim loại, gỗ trong nhà và ngoài trời.",
      descriptionEn: "Dulux Maxilite enamel is suitable for interior & exterior wood and metal surfaces.",
      features: "Độ phủ cao, Màng sơn bóng mượt, Khô nhanh chóng, Dễ dàng thi công",
      featuresEn: "High coverage, Gloss finish, Quick dry, Easy application",
      coverage: 13.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6-8 giờ.",
      paintType: PaintType.WOOD,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WOOD, SurfaceType.METAL],
      volume: 1.00,
      volumeUnit: "L",
      price: 180000.00,
      costPrice: 120000.00,
      stock: 90,
      colors: ["0001", "3003", "4002", "9001"],
    },
    {
      sku: "NIP-BIL-01L",
      name: "Sơn Dầu Cao Cấp Nippon Bilac Cho Gỗ & Sắt 1L",
      nameEn: "Nippon Bilac Wood & Metal Enamel 1L",
      slug: "nippon-bilac-wood-metal-1l",
      categoryId: categoriesMap["son-go-kim-loai"],
      supplierId: suppliersMap["nippon"],
      description: "Nippon Bilac là loại sơn gốc Alkyd cao cấp giúp chống rỉ sét và bảo vệ tốt nhất bề mặt sắt thép.",
      descriptionEn: "Nippon Bilac is a premium Alkyd enamel, preventing rust and protecting metal structures.",
      features: "Chống rỉ sét vượt trội, Màu sắc láng mịn bóng bẩy, Độ bền thời tiết cao",
      featuresEn: "Rust resistant, Smooth gloss, Weather resistant",
      coverage: 13.50,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6 giờ.",
      paintType: PaintType.METAL,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WOOD, SurfaceType.METAL],
      volume: 1.00,
      volumeUnit: "L",
      price: 195000.00,
      costPrice: 130000.00,
      stock: 75,
      colors: ["0001", "3003", "4002", "9001"],
    },
    {
      sku: "TOA-GLI-01L",
      name: "Sơn Dầu Cao Cấp TOA Glipton Cho Kim Loại 1L",
      nameEn: "TOA Glipton Premium Enamel 1L",
      slug: "toa-glipton-metal-1l",
      categoryId: categoriesMap["son-go-kim-loai"],
      supplierId: suppliersMap["toa"],
      description: "TOA Glipton là dòng sơn alkyd chất lượng thượng hạng mang lại màng sơn bóng mịn như gương.",
      descriptionEn: "TOA Glipton is a top-quality alkyd enamel, delivering a mirror-like gloss finish.",
      features: "Độ bóng gương tuyệt đỉnh, Chống rỉ sét cực tốt, Mùi nhẹ",
      featuresEn: "Mirror gloss finish, Anti-rust, Low odor",
      coverage: 14.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6 giờ.",
      paintType: PaintType.METAL,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WOOD, SurfaceType.METAL],
      volume: 1.00,
      volumeUnit: "L",
      price: 190000.00,
      costPrice: 125000.00,
      stock: 85,
      colors: ["0001", "3003", "4002", "9001"],
    },
    {
      sku: "KAN-FTS-01L",
      name: "Sơn Dầu Kansai Ftax Enamel Cho Gỗ & Sắt 1L",
      nameEn: "Kansai Ftax Enamel Wood & Metal 1L",
      slug: "kansai-ftax-enamel-1l",
      categoryId: categoriesMap["son-go-kim-loai"],
      supplierId: suppliersMap["kansai"],
      description: "Sơn dầu Kansai Ftax bảo vệ chống ăn mòn hiệu quả cho bề mặt gỗ và sắt thép cả trong và ngoài nhà.",
      descriptionEn: "Kansai Ftax protective enamel prevents corrosion on interior & exterior wood & metal.",
      features: "Chống ăn mòn thời tiết tốt, Bám dính cao, Giá thành kinh tế",
      featuresEn: "Corrosion resistant, Great adhesion, Economical",
      coverage: 13.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 6 giờ.",
      paintType: PaintType.WOOD,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.WOOD, SurfaceType.METAL],
      volume: 1.00,
      volumeUnit: "L",
      price: 1850000.00,
      costPrice: 120000.00,
      stock: 70,
      colors: ["0001", "3003", "4002", "9001"],
    },

    // ----------------------------------------------------
    // CATEGORY 6: Sơn Đặc Biệt (son-dac-biet)
    // ----------------------------------------------------
    {
      sku: "JOT-MAJ-ART-05L",
      name: "Sơn Hiệu Ứng Nghệ Thuật Jotun Majestic Design 5L",
      nameEn: "Jotun Majestic Design Art Effects 5L",
      slug: "jotun-majestic-design-art-effects-5l",
      categoryId: categoriesMap["son-dac-biet"],
      supplierId: suppliersMap["jotun"],
      description: "Sơn hiệu ứng Majestic Design mang lại bề mặt tường hoàn thiện lấp lánh như kim cương hay dịu dàng như cát sa mạc.",
      descriptionEn: "Majestic Design creates a sparkling diamond finish or gentle desert sand effects.",
      features: "Hiệu ứng lấp lánh ánh kim, Không mùi độc hại, Lau chùi nhẹ nhàng",
      featuresEn: "Metallic shimmer, Odorless, Lightly washable",
      coverage: 8.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.SPECIALTY,
      finish: PaintFinish.EGGSHELL,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1850000.00,
      costPrice: 1200000.00,
      stock: 15,
      isFeatured: false,
      colors: ["1001", "2002", "3004", "7002", "8002"],
    },
    {
      sku: "DUL-AMB-TXT-05L",
      name: "Sơn Hiệu Ứng Dulux Ambiance Velvet Gold 5L",
      nameEn: "Dulux Ambiance Velvet Gold Textures 5L",
      slug: "dulux-ambiance-velvet-gold-5l",
      categoryId: categoriesMap["son-dac-biet"],
      supplierId: suppliersMap["dulux"],
      description: "Sơn hiệu ứng vải nhung mịn ánh vàng Ambiance Velvet Gold đem lại không gian sống cổ điển sang trọng bậc nhất.",
      descriptionEn: "Dulux Ambiance Velvet Gold delivers a classic ultra-luxurious velvet gold texture.",
      features: "Hiệu ứng vải nhung mịn màng, Sắc vàng ánh kim xa hoa, Chống bám bẩn",
      featuresEn: "Velvet textured finish, Luxurious gold metallic, Stain resistant",
      coverage: 7.50,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.SPECIALTY,
      finish: PaintFinish.SATIN,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1950000.00,
      costPrice: 1300000.00,
      stock: 10,
      isFeatured: false,
      colors: ["2001", "2002", "4002"],
    },
    {
      sku: "NIP-MOM-05L",
      name: "Sơn Hiệu Ứng Nghệ Thuật Nippon Momento Elegant 5L",
      nameEn: "Nippon Momento Elegant Art Effect 5L",
      slug: "nippon-momento-elegant-5l",
      categoryId: categoriesMap["son-dac-biet"],
      supplierId: suppliersMap["nippon"],
      description: "Nippon Momento Elegant mang nét cổ điển độc đáo, khơi gợi cảm hứng sáng tạo vô tận cho bức tường nghệ thuật.",
      descriptionEn: "Nippon Momento Elegant inspires infinite creativity for elegant artistic accent walls.",
      features: "Hiệu ứng vân cát nhám lấp lánh, Độ bền cao, Ít mùi hắc",
      featuresEn: "Sparkling sand texture, High durability, Low odor",
      coverage: 8.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 2 giờ. Sơn lớp tiếp theo: 4 giờ.",
      paintType: PaintType.SPECIALTY,
      finish: PaintFinish.SATIN,
      surfaces: [SurfaceType.WALL],
      volume: 5.00,
      volumeUnit: "L",
      price: 1750000.00,
      costPrice: 1100000.00,
      stock: 12,
      isFeatured: false,
      colors: ["1001", "2001", "3004"],
    },
    {
      sku: "TOA-EPO-05L",
      name: "Sơn Sàn Epoxy TOA 2 Thành Phần Chống Bám Bụi 5L",
      nameEn: "TOA 2-Pack Epoxy Floor Coating 5L",
      slug: "toa-epoxy-floor-paint-5l",
      categoryId: categoriesMap["son-dac-biet"],
      supplierId: suppliersMap["toa"],
      description: "Sơn sàn Epoxy TOA 2 thành phần chịu lực cao lực, thích hợp cho sàn nhà xưởng, tầng hầm hay phòng sạch.",
      descriptionEn: "TOA 2-pack Epoxy Floor coating provides heavy-duty support, perfect for warehouses, basements or cleanrooms.",
      features: "Chịu lực chống trầy xước vượt trội, Chống hóa chất dầu mỡ cực tốt",
      featuresEn: "Extreme abrasion resistance, Chemical & oil resistant",
      coverage: 8.50,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 4 giờ. Sử dụng nhẹ: 24 giờ. Đạt độ cứng hoàn toàn: 7 ngày.",
      paintType: PaintType.SPECIALTY,
      finish: PaintFinish.SEMI_GLOSS,
      surfaces: [SurfaceType.CONCRETE],
      volume: 5.00,
      volumeUnit: "L",
      price: 1450000.00,
      costPrice: 950000.00,
      stock: 18,
      colors: ["3002", "3003", "8002"],
    },
    {
      sku: "KAN-EPO-05L",
      name: "Sơn Sàn Kansai K-Floor Epoxy Chống Trầy Xước 5L",
      nameEn: "Kansai K-Floor Epoxy Floor Coating 5L",
      slug: "kansai-kfloor-epoxy-5l",
      categoryId: categoriesMap["son-dac-biet"],
      supplierId: suppliersMap["kansai"],
      description: "Sơn sàn Kansai K-Floor Epoxy bóng cao, chống trơn trượt trầy xước, ngăn ẩm ngăn hóa chất mài mòn.",
      descriptionEn: "Kansai K-Floor Epoxy floor coating features high gloss, anti-slip, scratch-proof, and anti-chemical wear.",
      features: "Màng sơn bóng cao, Chống trơn trượt mài mòn, Dễ vệ sinh làm sạch",
      featuresEn: "High gloss finish, Anti-slip & abrasion proof, Easy clean",
      coverage: 9.00,
      coatsRequired: 2,
      dryingTime: "Khô bề mặt: 4 giờ. Sử dụng nhẹ: 24 giờ. Khô hoàn toàn: 7 ngày.",
      paintType: PaintType.SPECIALTY,
      finish: PaintFinish.GLOSS,
      surfaces: [SurfaceType.CONCRETE],
      volume: 5.00,
      volumeUnit: "L",
      price: 1550000.00,
      costPrice: 1000000.00,
      stock: 22,
      colors: ["3002", "3003", "8002"],
    }
  ];

  for (const p of paintsData) {
    const paint = await prisma.paint.upsert({
      where: { sku: p.sku },
      update: {},
      create: {
        sku: p.sku,
        name: p.name,
        nameEn: p.nameEn,
        slug: p.slug,
        categoryId: p.categoryId,
        supplierId: p.supplierId,
        description: p.description,
        descriptionEn: p.descriptionEn,
        features: p.features,
        featuresEn: p.featuresEn,
        coverage: p.coverage,
        coatsRequired: p.coatsRequired,
        dryingTime: p.dryingTime,
        paintType: p.paintType,
        finish: p.finish,
        surfaces: p.surfaces,
        volume: p.volume,
        volumeUnit: p.volumeUnit,
        price: p.price,
        costPrice: p.costPrice,
        stock: p.stock,
        isFeatured: p.isFeatured || false,
      },
    });

    // Create many-to-many bindings
    for (const colorCode of p.colors) {
      const colorId = colorsMap[colorCode];
      if (colorId) {
        await prisma.paintColorLink.upsert({
          where: {
            paintId_colorId: { paintId: paint.id, colorId: colorId },
          },
          update: {},
          create: {
            paintId: paint.id,
            colorId: colorId,
          },
        });
      }
    }
  }
  console.log("Paints and color mappings seeded successfully.");

  // 8. Dealers
  const dealersData = [
    { name: "Đại Lý Sơn SONVN Hà Nội", phone: "0243123456", email: "hanoi@sonvn.com", address: "Số 15 Cầu Giấy, Láng Thượng, Cầu Giấy", province: "Hà Nội", district: "Cầu Giấy", supplierSlug: "jotun", lat: 21.0264, lng: 105.8024 },
    { name: "Trung Tâm Phối Màu Jotun Tây Hồ", phone: "0243789456", email: "tayho@sonvn.com", address: "Số 102 Lạc Long Quân, Bưởi, Tây Hồ", province: "Hà Nội", district: "Tây Hồ", supplierSlug: "jotun", lat: 21.0602, lng: 105.8087 },
    { name: "Đại Lý Sơn Dulux Quận 1", phone: "0283999888", email: "q1@sonvn.com", address: "240 Trần Hưng Đạo, Nguyễn Cư Trinh, Quận 1", province: "Hồ Chí Minh", district: "Quận 1", supplierSlug: "dulux", lat: 10.7675, lng: 106.6914 },
    { name: "Nhà Phân Phối Sơn Jotun Bình Thạnh", phone: "0283511222", email: "binhthanh@sonvn.com", address: "45 Điện Biên Phủ, Phường 15, Bình Thạnh", province: "Hồ Chí Minh", district: "Bình Thạnh", supplierSlug: "jotun", lat: 10.7981, lng: 106.7049 },
    { name: "Đại Lý Sơn Nippon Đà Nẵng", phone: "02363555777", email: "danang@sonvn.com", address: "98 Nguyễn Văn Linh, Nam Dương, Hải Châu", province: "Đà Nẵng", district: "Hải Châu", supplierSlug: "nippon", lat: 16.0603, lng: 108.2155 }
  ];

  for (const d of dealersData) {
    const supplierId = d.supplierSlug ? suppliersMap[d.supplierSlug] : null;
    await prisma.dealer.create({
      data: {
        name: d.name,
        phone: d.phone,
        email: d.email,
        address: d.address,
        province: d.province,
        district: d.district,
        latitude: d.lat,
        longitude: d.lng,
        supplierId: supplierId,
      },
    });
  }
  console.log("Dealers seeded successfully.");

  // 9. Blogs
  const blogsData = [
    {
      title: "Top 10 Xu Hướng Màu Sơn Nhà Đẹp Trong Năm 2026",
      titleEn: "Top 10 Beautiful Home Paint Color Trends In 2026",
      slug: "top-10-xu-huong-mau-son-nha-2026",
      summary: "Khám phá các tông màu be ấm, xanh rêu thanh bình và màu đất sét được dự báo sẽ thống trị ngành thiết kế kiến trúc nội thất năm 2026.",
      summaryEn: "Explore warm beige, peaceful moss green, and terracotta colors predicted to dominate interior design in 2026.",
      content: "Xu hướng màu sắc năm 2026 chứng kiến sự chuyển dịch mạnh mẽ hướng về thiên nhiên và sự mộc mạc. Các tông màu như Kem Vani, Be Cát và đặc biệt là Xanh Rêu mang lại cảm giác an tâm, nhẹ nhàng cho ngôi nhà của bạn. Bài viết này hướng dẫn bạn cách phối hợp các màu sắc này cho phòng khách, phòng ngủ và mặt tiền nhà hợp xu thế nhất.",
      contentEn: "Color trends in 2026 witness a shift towards nature and earthiness. Tones like Vanilla Cream, Desert Sand, and especially Moss Green deliver stability and peace. This guide shares how to combine these colors for living rooms, bedrooms, and exteriors.",
    },
    {
      title: "Hướng Dẫn Tính Định Mức Sơn Đúng Kỹ Thuật Tránh Lãng Phí",
      titleEn: "Guide To Calculating Paint Coverage Properly To Avoid Waste",
      slug: "huong-dan-tinh-dinh-muc-son-dung-ky-thuat",
      summary: "Hướng dẫn chi tiết cách đo diện tích tường thực tế, cách trừ đi diện tích cửa sổ, cửa chính và cách quy đổi số lít sơn thành thùng thực tế.",
      summaryEn: "Detailed guide on measuring real wall areas, subtracting door and window dimensions, and converting paint liters to physical cans.",
      content: "Để bắt đầu sơn nhà, việc tính toán chuẩn lượng sơn vô cùng quan trọng. Công thức chuẩn: Diện tích sơn = 2 x (Chiều dài + Chiều rộng) x Chiều cao - (Diện tích cửa). Thông thường các loại sơn phủ nội thất có định mức 10-12 m2/lít/lớp. Do đó, bạn cần sơn ít nhất 2 lớp phủ và 1 lớp lót để màu sắc đạt chuẩn và bền lâu nhất.",
      contentEn: "To paint a house, calculating the exact quantity of paint is essential. Standard formula: Paint Area = 2 x (Length + Width) x Height - (Doors & Windows Area). Interior paints cover roughly 10-12 sqm/liter/coat. You need 2 top coats and 1 primer coat for perfect results.",
    }
  ];

  for (const b of blogsData) {
    await prisma.blog.upsert({
      where: { slug: b.slug },
      update: {},
      create: {
        title: b.title,
        titleEn: b.titleEn,
        slug: b.slug,
        summary: b.summary,
        summaryEn: b.summaryEn,
        content: b.content,
        contentEn: b.contentEn,
        authorId: adminUser.id,
      },
    });
  }
  console.log("Blogs seeded successfully.");

  console.log("Seeding process completed successfully!");
}

main()
  .catch((e) => {
    console.error("Error seeding database: ", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
